insert into public.exercises (stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable) values
('reconditioning-core-breathing-brace','draft','1.0.0',2,6,5,20,5,'slow-controlled',false),
('reconditioning-core-sit-to-stand','draft','1.0.0',3,8,0,45,3,'controlled',false),
('reconditioning-core-supported-march','draft','1.0.0',3,10,0,30,4,'controlled',false),
('reconditioning-core-supported-balance','draft','1.0.0',3,3,20,30,4,'steady',false),
('reconditioning-core-pelvic-floor-coordination','draft','1.0.0',2,6,3,20,5,'slow-controlled',false)
on conflict (stable_key) do update set status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,default_tempo=excluded.default_tempo;

insert into public.exercise_translations (exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications from public.exercises e join (values
('reconditioning-core-breathing-brace','fr','Respiration et gainage doux','Coordination respiration-tronc','Assis ou allongé confortablement.','Expirez doucement et engagez légèrement l’abdomen sans bloquer la respiration.','Réintroduire le contrôle du tronc avec faible charge.','Effort léger, respiration normale.','Bloquer la respiration ou pousser fortement.','Restez confortable et évitez tout effort maximal.','Arrêtez en cas de douleur vive, malaise ou essoufflement inhabituel.','À adapter après chirurgie, grossesse/post-partum ou restriction abdominale.'),
('reconditioning-core-breathing-brace','en','Breathing with gentle brace','Breathing-trunk coordination','Sit or lie comfortably.','Breathe out gently and lightly engage the abdomen without holding your breath.','Reintroduce trunk control with low loading.','Keep effort light and breathing normal.','Holding the breath or straining hard.','Stay comfortable and avoid maximal effort.','Stop for sharp pain, faintness, or unusual breathlessness.','Modify after surgery, pregnancy/postpartum, or abdominal restrictions.'),
('reconditioning-core-breathing-brace','de','Atmung mit sanfter Rumpfspannung','Koordination von Atmung und Rumpf','Bequem sitzen oder liegen.','Sanft ausatmen und Bauch leicht anspannen, ohne Luft anzuhalten.','Rumpfkontrolle mit geringer Belastung wieder aufbauen.','Leichte Anspannung und normal weiteratmen.','Luft anhalten oder stark pressen.','Komfortabel bleiben und Maximalkraft vermeiden.','Bei stechendem Schmerz, Kreislaufproblemen oder ungewöhnlicher Atemnot abbrechen.','Nach Operation, Schwangerschaft/Wochenbett oder abdominalen Einschränkungen anpassen.'),
('reconditioning-core-sit-to-stand','fr','Assis-debout fonctionnel','Force des jambes et autonomie','Assis sur chaise stable, pieds au sol.','Penchez légèrement le tronc, levez-vous puis asseyez-vous avec contrôle.','Renforcer un transfert essentiel à l’autonomie.','Utilisez les accoudoirs si nécessaire.','Se lever trop vite ou se laisser tomber.','Chaise stable et espace dégagé.','Arrêtez en cas de vertige, douleur vive ou perte d’équilibre.','À adapter si les transferts ou l’appui sont limités.'),
('reconditioning-core-sit-to-stand','en','Functional sit-to-stand','Leg strength and independence','Sit on a stable chair with feet supported.','Lean slightly forward, stand, then sit down with control.','Strengthen a key transfer for independence.','Use armrests if needed.','Standing too quickly or dropping into the chair.','Use a stable chair and clear space.','Stop for dizziness, sharp pain, or loss of balance.','Modify if transfers or weight bearing are restricted.'),
('reconditioning-core-sit-to-stand','de','Funktionelles Aufstehen','Beinkraft und Selbstständigkeit','Auf stabilem Stuhl sitzen, Füße am Boden.','Oberkörper leicht vor, aufstehen und kontrolliert wieder hinsetzen.','Wichtigen Transfer für Selbstständigkeit stärken.','Bei Bedarf Armlehnen nutzen.','Zu schnell aufstehen oder fallen lassen.','Stabilen Stuhl und freien Raum nutzen.','Bei Schwindel, stechendem Schmerz oder Gleichgewichtsverlust abbrechen.','Bei eingeschränkten Transfers oder Belastung anpassen.'),
('reconditioning-core-supported-march','fr','Marche sur place avec appui','Endurance légère et coordination','Debout près d’un support stable.','Levez alternativement un pied puis l’autre à petite hauteur.','Préparer marche et reconditionnement général.','Petits pas réguliers.','Lever trop haut ou perdre le contrôle.','Gardez un support à portée.','Arrêtez en cas de vertige, douleur, essoufflement inhabituel ou instabilité.','À adapter si la station debout ou la marche n’est pas sûre.'),
('reconditioning-core-supported-march','en','Supported marching','Light endurance and coordination','Stand near stable support.','Alternately lift one foot then the other a small distance.','Prepare walking and general reconditioning.','Use small steady steps.','Lifting too high or losing control.','Keep support within reach.','Stop for dizziness, pain, unusual breathlessness, or instability.','Modify if standing or walking is unsafe.'),
('reconditioning-core-supported-march','de','Marschieren mit Unterstützung','Leichte Ausdauer und Koordination','Nahe einer stabilen Stütze stehen.','Abwechselnd einen Fuß und dann den anderen leicht anheben.','Gehen und allgemeine Rekonditionierung vorbereiten.','Kleine gleichmäßige Schritte.','Zu hoch anheben oder Kontrolle verlieren.','Stütze in Reichweite halten.','Bei Schwindel, Schmerz, ungewöhnlicher Atemnot oder Instabilität abbrechen.','Bei unsicherem Stehen oder Gehen anpassen.'),
('reconditioning-core-supported-balance','fr','Équilibre avec appui','Équilibre et contrôle postural','Debout près d’un support stable.','Rapprochez légèrement les pieds ou transférez doucement le poids selon votre niveau.','Améliorer l’équilibre avec un environnement sécurisé.','Gardez toujours le support accessible.','Fermer les yeux ou supprimer l’appui trop tôt.','Surface stable, chaussures adaptées si nécessaire.','Arrêtez en cas de vertige ou perte d’équilibre.','À éviter sans assistance si le risque de chute est élevé.'),
('reconditioning-core-supported-balance','en','Supported balance','Balance and postural control','Stand near stable support.','Bring the feet slightly closer or gently shift weight according to your level.','Improve balance in a safer environment.','Keep support within reach.','Closing the eyes or removing support too early.','Use a stable surface and appropriate footwear if needed.','Stop for dizziness or loss of balance.','Avoid without assistance if fall risk is high.'),
('reconditioning-core-supported-balance','de','Gleichgewicht mit Unterstützung','Gleichgewicht und Haltungskontrolle','Nahe einer stabilen Stütze stehen.','Füße leicht enger stellen oder Gewicht je nach Niveau sanft verlagern.','Gleichgewicht in sicherer Umgebung verbessern.','Stütze immer erreichbar halten.','Augen schließen oder Stütze zu früh entfernen.','Stabile Fläche und bei Bedarf geeignetes Schuhwerk.','Bei Schwindel oder Gleichgewichtsverlust abbrechen.','Bei hohem Sturzrisiko nicht ohne Hilfe.'),
('reconditioning-core-pelvic-floor-coordination','fr','Coordination respiration–plancher pelvien','Conscience et coordination pelvienne douce','Assis ou allongé confortablement.','À l’expiration, imaginez une légère fermeture et élévation du plancher pelvien puis relâchez complètement à l’inspiration.','Introduire une coordination douce sans poussée ni effort maximal.','Le relâchement est aussi important que la contraction.','Serrer fort, bloquer la respiration ou pousser vers le bas.','Aucun effort maximal; adaptez en grossesse et post-partum selon avis professionnel.','Arrêtez en cas de douleur pelvienne, pression lourde, saignement ou symptômes nouveaux.','À adapter en grossesse/post-partum, prolapsus symptomatique, douleur pelvienne ou postopératoire.'),
('reconditioning-core-pelvic-floor-coordination','en','Breathing–pelvic floor coordination','Gentle pelvic awareness and coordination','Sit or lie comfortably.','As you breathe out, imagine a gentle pelvic-floor closure and lift, then fully relax on the inhale.','Introduce gentle coordination without straining or maximal effort.','Relaxation matters as much as contraction.','Squeezing hard, holding the breath, or bearing down.','No maximal effort; adapt in pregnancy/postpartum with professional guidance.','Stop for pelvic pain, heavy pressure, bleeding, or new symptoms.','Modify in pregnancy/postpartum, symptomatic prolapse, pelvic pain, or after surgery.'),
('reconditioning-core-pelvic-floor-coordination','de','Atmung–Beckenboden-Koordination','Sanfte Wahrnehmung und Koordination des Beckenbodens','Bequem sitzen oder liegen.','Beim Ausatmen eine leichte Beckenbodenschließung und Anhebung vorstellen, beim Einatmen vollständig lösen.','Sanfte Koordination ohne Pressen oder Maximalkraft einführen.','Entspannung ist genauso wichtig wie Anspannung.','Stark pressen, Luft anhalten oder nach unten drücken.','Keine Maximalkraft; in Schwangerschaft/Wochenbett professionell anpassen.','Bei Beckenschmerz, starkem Druckgefühl, Blutung oder neuen Symptomen abbrechen.','Bei Schwangerschaft/Wochenbett, symptomatischem Prolaps, Beckenschmerz oder postoperativ anpassen.')
) v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications) on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;
insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'full-body',true from public.exercises where stable_key in ('reconditioning-core-breathing-brace','reconditioning-core-sit-to-stand','reconditioning-core-supported-march','reconditioning-core-supported-balance','reconditioning-core-pelvic-floor-coordination') on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;
insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'pelvic-floor',false from public.exercises where stable_key='reconditioning-core-pelvic-floor-coordination' on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;
insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.exercises e join (values
('reconditioning-core-sit-to-stand','high-chair-arms','easy',0,2,6,null::integer,45,'controlled'),('reconditioning-core-sit-to-stand','standard-chair','standard',1,3,8,null::integer,45,'controlled'),('reconditioning-core-sit-to-stand','slow-lowering','hard',2,3,8,null::integer,60,'3-second-lowering'),
('reconditioning-core-supported-balance','wide-stance-supported','easy',0,3,3,15,30,'steady'),('reconditioning-core-supported-balance','narrow-stance-supported','standard',1,3,3,20,30,'steady'),('reconditioning-core-supported-balance','reduced-hand-support','hard',2,3,3,20,45,'steady')) v(exercise_key,stable_key,difficulty,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;
insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.tip from public.exercise_variants ev join public.exercises e on e.id=ev.exercise_id join (values
('reconditioning-core-sit-to-stand','high-chair-arms','fr','Chaise haute avec appui','Chaise plus haute et accoudoirs si besoin.','Sécurité d’abord.'),('reconditioning-core-sit-to-stand','high-chair-arms','en','High chair with arm support','Use a higher chair and armrests if needed.','Safety first.'),('reconditioning-core-sit-to-stand','high-chair-arms','de','Hoher Stuhl mit Armstütze','Höheren Stuhl und Armlehnen nutzen.','Sicherheit zuerst.'),
('reconditioning-core-sit-to-stand','standard-chair','fr','Assis-debout standard','Levez-vous puis asseyez-vous avec contrôle.','Gardez les pieds stables.'),('reconditioning-core-sit-to-stand','standard-chair','en','Standard sit-to-stand','Stand and sit with control.','Keep the feet stable.'),('reconditioning-core-sit-to-stand','standard-chair','de','Standard Aufstehen','Kontrolliert aufstehen und hinsetzen.','Füße stabil halten.'),
('reconditioning-core-sit-to-stand','slow-lowering','fr','Descente lente','Descendez en environ trois secondes.','Contrôlez la fin du mouvement.'),('reconditioning-core-sit-to-stand','slow-lowering','en','Slow lowering','Lower over about three seconds.','Control the end of the movement.'),('reconditioning-core-sit-to-stand','slow-lowering','de','Langsames Hinsetzen','Über etwa drei Sekunden absenken.','Bewegungsende kontrollieren.'),
('reconditioning-core-supported-balance','wide-stance-supported','fr','Appui large avec soutien','Pieds plus écartés, mains proches du support.','Commencez stable.'),('reconditioning-core-supported-balance','wide-stance-supported','en','Wide stance with support','Stand wider with hands near support.','Start stable.'),('reconditioning-core-supported-balance','wide-stance-supported','de','Breiter Stand mit Stütze','Breiter stehen, Hände nahe der Stütze.','Stabil beginnen.'),
('reconditioning-core-supported-balance','narrow-stance-supported','fr','Appui rapproché avec soutien','Rapprochez les pieds tout en gardant le support.','Réduisez progressivement la base.'),('reconditioning-core-supported-balance','narrow-stance-supported','en','Narrow stance with support','Bring the feet closer while keeping support.','Reduce the base gradually.'),('reconditioning-core-supported-balance','narrow-stance-supported','de','Engerer Stand mit Stütze','Füße enger stellen, Stütze behalten.','Standfläche schrittweise verkleinern.'),
('reconditioning-core-supported-balance','reduced-hand-support','fr','Appui manuel réduit','Allégez les mains uniquement si stable.','Le support reste accessible.'),('reconditioning-core-supported-balance','reduced-hand-support','en','Reduced hand support','Lighten hand support only if stable.','Keep support within reach.'),('reconditioning-core-supported-balance','reduced-hand-support','de','Weniger Handstütze','Handstütze nur bei Stabilität reduzieren.','Stütze erreichbar halten.')) t(exercise_key,variant_key,language,name,instructions,tip) on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;