insert into public.exercises (stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable) values
('special-populations-breathing-pacing','draft','1.0.0',2,6,5,30,5,'slow-controlled',false),
('special-populations-seated-mobility','draft','1.0.0',2,8,0,30,5,'slow-controlled',false),
('special-populations-supported-sit-to-stand','draft','1.0.0',2,6,0,60,3,'controlled',false),
('special-populations-supported-weight-shift','draft','1.0.0',3,6,0,30,4,'slow-controlled',false),
('special-populations-supported-march','draft','1.0.0',2,8,0,45,3,'controlled',false)
on conflict (stable_key) do update set status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,default_tempo=excluded.default_tempo;

insert into public.exercise_translations (exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications from public.exercises e join (values
('special-populations-breathing-pacing','fr','Respiration et gestion de l’effort','Respiration, récupération et dosage de l’effort','Assis ou allongé confortablement selon vos restrictions.','Respirez lentement et utilisez l’expiration pour relâcher les tensions; gardez une intensité faible.','Créer un point de départ commun pour gérer fatigue et tolérance à l’effort.','Arrêtez avant l’épuisement.','Retenir la respiration ou poursuivre malgré une fatigue inhabituelle.','Respectez les recommandations de votre équipe soignante, notamment en contexte neurologique, grossesse/post-partum ou maladie chronique.','Arrêtez et demandez une évaluation en cas de douleur thoracique, essoufflement inhabituel important, malaise, nouveau déficit neurologique ou autre symptôme aigu inquiétant.','À individualiser en cas de grossesse à risque, phase neurologique aiguë, décompensation médicale ou restriction spécifique.'),
('special-populations-breathing-pacing','en','Breathing and activity pacing','Breathing, recovery, and effort dosing','Sit or lie comfortably according to your restrictions.','Breathe slowly, use the exhale to release tension, and keep intensity low.','Provide a common starting point for fatigue and activity tolerance.','Stop before exhaustion.','Holding the breath or pushing through unusual fatigue.','Follow your treating team’s advice, especially with neurological conditions, pregnancy/postpartum, or chronic illness.','Stop and seek assessment for chest pain, marked unusual breathlessness, faintness, new neurological deficit, or another concerning acute symptom.','Individualise for high-risk pregnancy, acute neurological phase, medical decompensation, or specific restrictions.'),
('special-populations-breathing-pacing','de','Atmung und Belastungsdosierung','Atmung, Erholung und Belastungssteuerung','Bequem sitzen oder liegen entsprechend den Einschränkungen.','Langsam atmen, beim Ausatmen Spannung lösen und Intensität niedrig halten.','Gemeinsamen Einstieg für Fatigue und Belastungsverträglichkeit schaffen.','Vor Erschöpfung stoppen.','Luft anhalten oder trotz ungewöhnlicher Müdigkeit weitermachen.','Vorgaben des Behandlungsteams beachten, besonders bei neurologischen Erkrankungen, Schwangerschaft/Wochenbett oder chronischer Erkrankung.','Bei Brustschmerz, deutlich ungewöhnlicher Atemnot, Kreislaufproblemen, neuem neurologischem Defizit oder anderem akut bedenklichen Symptom abbrechen und abklären lassen.','Bei Risikoschwangerschaft, akuter neurologischer Phase, medizinischer Dekompensation oder speziellen Einschränkungen individualisieren.'),
('special-populations-seated-mobility','fr','Mobilité globale assise','Mobilité douce et coordination','Assis sur une chaise stable, pieds soutenus.','Alternez lentement ouverture des bras, petits mouvements des chevilles et légère rotation du tronc selon tolérance.','Entretenir le mouvement avec faible risque de chute.','Petite amplitude et rythme calme.','Mouvements rapides ou grande amplitude.','Restez soutenu et respectez toute asymétrie ou restriction connue.','Arrêtez en cas de vertige marqué, douleur vive, nouveau déficit ou aggravation nette des symptômes.','À adapter si la position assise ou certains mouvements sont contre-indiqués.'),
('special-populations-seated-mobility','en','Seated whole-body mobility','Gentle mobility and coordination','Sit on a stable chair with feet supported.','Slowly combine arm opening, small ankle movements, and gentle trunk rotation as tolerated.','Maintain movement with lower fall risk.','Use small range and calm pace.','Fast movements or large range.','Stay supported and respect known asymmetry or restrictions.','Stop for marked dizziness, sharp pain, a new deficit, or clear symptom worsening.','Modify if sitting or specific movements are contraindicated.'),
('special-populations-seated-mobility','de','Ganzkörpermobilität im Sitzen','Sanfte Beweglichkeit und Koordination','Auf stabilem Stuhl sitzen, Füße unterstützt.','Langsam Armöffnung, kleine Sprunggelenksbewegungen und sanfte Rumpfrotation kombinieren.','Bewegung bei geringerem Sturzrisiko erhalten.','Kleine Weite und ruhiges Tempo.','Schnelle oder große Bewegungen.','Gestützt bleiben und bekannte Asymmetrien oder Einschränkungen beachten.','Bei deutlichem Schwindel, stechendem Schmerz, neuem Defizit oder klarer Verschlechterung abbrechen.','Bei kontraindiziertem Sitzen oder bestimmten Bewegungen anpassen.'),
('special-populations-supported-sit-to-stand','fr','Assis-debout avec soutien','Force fonctionnelle et transfert','Assis sur une chaise stable, support ou aidant disponible si nécessaire.','Levez-vous avec l’aide nécessaire puis asseyez-vous lentement.','Travailler un transfert utile à l’autonomie.','La sécurité prime sur le nombre de répétitions.','Se lever sans aide alors qu’elle est nécessaire ou se laisser tomber.','Utilisez l’aide prescrite et respectez les limitations d’appui.','Arrêtez en cas de vertige, douleur vive, perte d’équilibre, faiblesse inhabituelle ou fatigue brutale.','À adapter si le transfert nécessite supervision, aide physique ou restriction d’appui.'),
('special-populations-supported-sit-to-stand','en','Supported sit-to-stand','Functional strength and transfers','Sit on a stable chair with support or assistance available if needed.','Stand with the required assistance, then sit down slowly.','Practice a transfer relevant to independence.','Safety matters more than repetition count.','Standing without needed assistance or dropping into the chair.','Use prescribed assistance and respect weight-bearing limits.','Stop for dizziness, sharp pain, loss of balance, unusual weakness, or sudden fatigue.','Modify when transfers require supervision, physical assistance, or weight-bearing restrictions.'),
('special-populations-supported-sit-to-stand','de','Aufstehen mit Unterstützung','Funktionelle Kraft und Transfers','Auf stabilem Stuhl sitzen, bei Bedarf Stütze oder Hilfe verfügbar.','Mit notwendiger Hilfe aufstehen und langsam wieder hinsetzen.','Für Selbstständigkeit wichtigen Transfer üben.','Sicherheit vor Wiederholungszahl.','Ohne nötige Hilfe aufstehen oder auf den Stuhl fallen lassen.','Verordnete Hilfe und Belastungsgrenzen beachten.','Bei Schwindel, stechendem Schmerz, Gleichgewichtsverlust, ungewöhnlicher Schwäche oder plötzlicher Erschöpfung abbrechen.','Bei notwendiger Aufsicht, körperlicher Hilfe oder Belastungseinschränkung anpassen.'),
('special-populations-supported-weight-shift','fr','Transfert de poids sécurisé','Équilibre et contrôle en station debout','Debout avec support stable et aide si nécessaire.','Déplacez doucement une petite partie du poids d’un côté puis de l’autre.','Travailler contrôle postural et préparation à la marche.','Petits transferts uniquement.','Supprimer l’appui trop tôt ou aller trop loin.','Support stable, environnement dégagé, assistance si prescrite.','Arrêtez en cas de vertige, perte d’équilibre, douleur ou nouveau symptôme neurologique.','À éviter sans assistance si le risque de chute est élevé.'),
('special-populations-supported-weight-shift','en','Supported weight shift','Balance and standing control','Stand with stable support and assistance if needed.','Gently shift a small amount of weight from one side to the other.','Practice postural control and walking preparation.','Use small shifts only.','Removing support too early or shifting too far.','Use stable support, clear space, and prescribed assistance.','Stop for dizziness, loss of balance, pain, or a new neurological symptom.','Avoid without assistance when fall risk is high.'),
('special-populations-supported-weight-shift','de','Gesicherte Gewichtsverlagerung','Gleichgewicht und Standkontrolle','Mit stabiler Stütze und bei Bedarf Hilfe stehen.','Kleine Gewichtsverlagerung von einer Seite zur anderen.','Haltungskontrolle und Gehvorbereitung üben.','Nur kleine Verlagerungen.','Stütze zu früh lösen oder zu weit verlagern.','Stabile Stütze, freier Raum und verordnete Hilfe nutzen.','Bei Schwindel, Gleichgewichtsverlust, Schmerz oder neuem neurologischem Symptom abbrechen.','Bei hohem Sturzrisiko nicht ohne Hilfe.'),
('special-populations-supported-march','fr','Marche sur place sécurisée','Marche, coordination et endurance légère','Debout avec support stable et aide si nécessaire.','Soulevez alternativement les pieds à petite hauteur et à rythme confortable.','Entretenir ou préparer la marche avec charge modérée.','Qualité et sécurité avant vitesse.','Lever trop haut ou continuer malgré la fatigue.','Utilisez support et aide prescrite; adaptez la durée à la fatigue.','Arrêtez en cas de vertige, essoufflement inhabituel, douleur, perte d’équilibre ou aggravation neurologique.','À adapter si la marche debout n’est pas sûre ou si la fatigue est importante.'),
('special-populations-supported-march','en','Supported marching','Walking, coordination, and light endurance','Stand with stable support and assistance if needed.','Alternately lift the feet a small distance at a comfortable pace.','Maintain or prepare walking with moderate demand.','Quality and safety before speed.','Lifting too high or pushing through fatigue.','Use prescribed support and assistance; adapt duration to fatigue.','Stop for dizziness, unusual breathlessness, pain, loss of balance, or neurological worsening.','Modify if standing walking is unsafe or fatigue is significant.'),
('special-populations-supported-march','de','Gesichertes Marschieren','Gehen, Koordination und leichte Ausdauer','Mit stabiler Stütze und bei Bedarf Hilfe stehen.','Füße abwechselnd leicht anheben, angenehmes Tempo.','Gehen mit moderater Belastung erhalten oder vorbereiten.','Qualität und Sicherheit vor Geschwindigkeit.','Zu hoch anheben oder trotz Erschöpfung weitermachen.','Verordnete Stütze/Hilfe nutzen und Dauer an Fatigue anpassen.','Bei Schwindel, ungewöhnlicher Atemnot, Schmerz, Gleichgewichtsverlust oder neurologischer Verschlechterung abbrechen.','Bei unsicherem Stehen/Gehen oder starker Fatigue anpassen.')
) v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications) on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;
insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'full-body',true from public.exercises where stable_key in ('special-populations-breathing-pacing','special-populations-seated-mobility','special-populations-supported-sit-to-stand','special-populations-supported-weight-shift','special-populations-supported-march') on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;
insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.exercises e join (values
('special-populations-supported-sit-to-stand','high-chair-full-support','easy',0,2,4,null::integer,60,'controlled'),('special-populations-supported-sit-to-stand','standard-supported','standard',1,2,6,null::integer,60,'controlled'),('special-populations-supported-sit-to-stand','slow-lowering-supported','hard',2,3,6,null::integer,75,'3-second-lowering'),
('special-populations-supported-march','short-bout','easy',0,2,6,null::integer,45,'controlled'),('special-populations-supported-march','standard-bout','standard',1,2,8,null::integer,45,'controlled'),('special-populations-supported-march','longer-bout','hard',2,3,8,null::integer,60,'controlled')) v(exercise_key,stable_key,difficulty,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;
insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.tip from public.exercise_variants ev join public.exercises e on e.id=ev.exercise_id join (values
('special-populations-supported-sit-to-stand','high-chair-full-support','fr','Chaise haute et soutien complet','Utilisez chaise haute, accoudoirs et aide nécessaire.','Sécurité maximale.'),('special-populations-supported-sit-to-stand','high-chair-full-support','en','High chair with full support','Use a higher chair, armrests, and needed assistance.','Maximise safety.'),('special-populations-supported-sit-to-stand','high-chair-full-support','de','Hoher Stuhl mit voller Unterstützung','Höheren Stuhl, Armlehnen und nötige Hilfe nutzen.','Maximale Sicherheit.'),
('special-populations-supported-sit-to-stand','standard-supported','fr','Assis-debout soutenu standard','Utilisez le soutien nécessaire pour vous lever et vous rasseoir.','Gardez le contrôle.'),('special-populations-supported-sit-to-stand','standard-supported','en','Standard supported sit-to-stand','Use needed support to stand and sit.','Keep control.'),('special-populations-supported-sit-to-stand','standard-supported','de','Standard Aufstehen mit Stütze','Nötige Unterstützung beim Aufstehen/Hinsetzen nutzen.','Kontrolle behalten.'),
('special-populations-supported-sit-to-stand','slow-lowering-supported','fr','Descente lente soutenue','Asseyez-vous lentement avec soutien.','Ne réduisez pas l’aide trop tôt.'),('special-populations-supported-sit-to-stand','slow-lowering-supported','en','Supported slow lowering','Sit down slowly with support.','Do not reduce assistance too early.'),('special-populations-supported-sit-to-stand','slow-lowering-supported','de','Langsames Hinsetzen mit Stütze','Mit Unterstützung langsam hinsetzen.','Hilfe nicht zu früh reduzieren.'),
('special-populations-supported-march','short-bout','fr','Marche courte','Effectuez une courte série de pas sur place.','Arrêtez avant la fatigue.'),('special-populations-supported-march','short-bout','en','Short marching bout','Perform a short bout of marching in place.','Stop before fatigue.'),('special-populations-supported-march','short-bout','de','Kurze Marschierphase','Kurze Serie am Platz marschieren.','Vor Erschöpfung stoppen.'),
('special-populations-supported-march','standard-bout','fr','Marche standard','Marchez sur place à rythme confortable.','Support toujours accessible.'),('special-populations-supported-march','standard-bout','en','Standard marching','March in place at a comfortable pace.','Keep support within reach.'),('special-populations-supported-march','standard-bout','de','Standard Marschieren','In angenehmem Tempo am Platz marschieren.','Stütze erreichbar halten.'),
('special-populations-supported-march','longer-bout','fr','Marche prolongée','Augmentez légèrement la durée si bien tolérée.','Durée avant intensité.'),('special-populations-supported-march','longer-bout','en','Longer marching bout','Increase duration slightly if well tolerated.','Duration before intensity.'),('special-populations-supported-march','longer-bout','de','Längere Marschierphase','Dauer bei guter Verträglichkeit leicht erhöhen.','Dauer vor Intensität.')) t(exercise_key,variant_key,language,name,instructions,tip) on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;