insert into public.exercises (
  stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable
) values
('head-neck-breathing-relaxation','draft','1.0.0',2,6,5,20,5,'slow-controlled',false),
('head-neck-gentle-rotation','draft','1.0.0',2,6,0,20,5,'slow-controlled',false),
('head-neck-cervical-retraction','draft','1.0.0',3,8,3,30,4,'controlled',false),
('head-neck-scapular-setting','draft','1.0.0',3,8,5,30,4,'isometric',false),
('head-neck-jaw-relaxation','draft','1.0.0',2,6,3,20,5,'slow-controlled',false)
on conflict (stable_key) do update set
  status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,
  default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,
  default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,
  default_tempo=excluded.default_tempo;

insert into public.exercise_translations (
  exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications
)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('head-neck-breathing-relaxation','fr','Respiration et relâchement cervical','Détente de la nuque, respiration et contrôle postural','Assis ou allongé confortablement, épaules relâchées et tête soutenue si nécessaire.','Respirez lentement et laissez les épaules descendre. À l’expiration, relâchez volontairement la mâchoire et les muscles de la nuque sans forcer de mouvement.','Réduire les tensions inutiles et préparer un mouvement cervical plus confortable.','Cherchez le relâchement, pas une contraction forte.','Hausser les épaules, serrer les dents ou bloquer la respiration.','Restez dans une position stable. En cas de vertiges, évitez les changements rapides de position de la tête.','Arrêtez en cas de vertige important ou inhabituel, vision double, malaise, nouvelle faiblesse ou engourdissement, difficulté à parler ou avaler, ou céphalée soudaine et intense.','À adapter si la position choisie déclenche fortement les vertiges ou si une restriction cervicale médicale a été prescrite.'),
('head-neck-breathing-relaxation','en','Breathing and neck relaxation','Neck relaxation, breathing and postural control','Sit or lie comfortably with the shoulders relaxed and the head supported if needed.','Breathe slowly and let the shoulders drop. As you breathe out, gently relax the jaw and neck muscles without forcing movement.','Reduce unnecessary tension and prepare for more comfortable neck movement.','Aim for relaxation rather than strong contraction.','Shrugging the shoulders, clenching the teeth, or holding the breath.','Stay in a stable position. If dizziness is present, avoid rapid head-position changes.','Stop for severe or unusual dizziness, double vision, faintness, new weakness or numbness, difficulty speaking or swallowing, or a sudden severe headache.','Modify if the chosen position strongly provokes dizziness or if medical neck restrictions have been prescribed.'),
('head-neck-breathing-relaxation','de','Atmung und Nackenentspannung','Nackenentspannung, Atmung und Haltungskontrolle','Sitzen oder liegen Sie bequem, Schultern entspannt, Kopf bei Bedarf unterstützt.','Atmen Sie langsam und lassen Sie die Schultern sinken. Entspannen Sie beim Ausatmen sanft Kiefer- und Nackenmuskulatur, ohne Bewegung zu erzwingen.','Unnötige Spannung reduzieren und angenehmere Halsbewegung vorbereiten.','Entspannung statt starker Anspannung anstreben.','Schultern hochziehen, Zähne zusammenpressen oder Luft anhalten.','Bleiben Sie in einer stabilen Position. Bei Schwindel schnelle Kopfpositionswechsel vermeiden.','Bei starkem oder ungewöhnlichem Schwindel, Doppelbildern, Kreislaufproblemen, neuer Schwäche oder Taubheit, Sprach-/Schluckstörungen oder plötzlich sehr starken Kopfschmerzen abbrechen.','Anpassen, wenn die Position starken Schwindel auslöst oder medizinische Nackeneinschränkungen bestehen.'),

('head-neck-gentle-rotation','fr','Rotation cervicale douce','Mobilité cervicale contrôlée','Assis droit et stable, regard à l’horizontale, épaules relâchées.','Tournez lentement la tête d’un côté dans une petite amplitude confortable, revenez au centre puis changez de côté.','Entretenir une mobilité cervicale utile aux activités quotidiennes.','Le mouvement doit être lent, petit et sans à-coup.','Forcer en fin d’amplitude, aller vite ou incliner la tête pendant la rotation.','Si vous avez des vertiges, réduisez l’amplitude et évitez tout mouvement rapide ou position provocatrice non évaluée.','Arrêtez en cas de vertige marqué, nausée importante, vision double, douleur vive, irradiation nouvelle, faiblesse ou engourdissement nouveau.','À éviter ou adapter si la rotation cervicale est médicalement limitée ou déclenche des symptômes neurologiques/vestibulaires importants.'),
('head-neck-gentle-rotation','en','Gentle neck rotation','Controlled cervical mobility','Sit upright and stable with eyes level and shoulders relaxed.','Slowly turn the head to one side through a small comfortable range, return to center, then repeat to the other side.','Maintain neck mobility useful for everyday activities.','Keep the movement slow, small, and smooth.','Forcing end range, moving quickly, or tilting the head during rotation.','If dizziness is present, reduce the range and avoid rapid or unassessed provocative head positions.','Stop for marked dizziness, significant nausea, double vision, sharp pain, new radiating symptoms, weakness, or numbness.','Avoid or modify if neck rotation is medically restricted or triggers significant neurological or vestibular symptoms.'),
('head-neck-gentle-rotation','de','Sanfte Halsrotation','Kontrollierte Halswirbelsäulenbeweglichkeit','Sitzen Sie aufrecht und stabil, Blick horizontal, Schultern entspannt.','Drehen Sie den Kopf langsam in kleinem angenehmem Bereich zu einer Seite, zurück zur Mitte und dann zur anderen Seite.','Alltagsrelevante Halsbeweglichkeit erhalten.','Langsam, klein und ohne ruckartige Bewegung drehen.','Endstellung erzwingen, schnell bewegen oder den Kopf während der Drehung neigen.','Bei Schwindel Bewegungsweite reduzieren und schnelle oder nicht abgeklärte provokative Kopfpositionen vermeiden.','Bei deutlichem Schwindel, starker Übelkeit, Doppelbildern, stechendem Schmerz, neuer Ausstrahlung, Schwäche oder Taubheit abbrechen.','Bei medizinisch eingeschränkter Rotation oder deutlichen neurologischen/vestibulären Symptomen vermeiden oder anpassen.'),

('head-neck-cervical-retraction','fr','Rétraction cervicale douce','Contrôle de la tête et alignement cervical','Assis contre un dossier ou debout de façon stable, regard horizontal.','Reculez très légèrement le menton comme pour allonger la nuque, sans baisser la tête. Maintenez brièvement puis relâchez.','Améliorer le contrôle cervical et la tolérance à une posture neutre.','Imaginez un petit mouvement horizontal, pas un grand double menton forcé.','Baisser la tête, pousser fort ou créer une douleur irradiée.','Commencez avec une amplitude minimale. Ne poursuivez pas si le mouvement augmente nettement les vertiges ou les symptômes neurologiques.','Arrêtez en cas de douleur vive, augmentation nette d’une douleur irradiée, vertige important, vision double, faiblesse ou engourdissement nouveau.','À adapter après chirurgie cervicale récente ou si ce mouvement est médicalement restreint.'),
('head-neck-cervical-retraction','en','Gentle cervical retraction','Head control and cervical alignment','Sit against a backrest or stand stably with eyes level.','Gently draw the chin straight backward as if lengthening the back of the neck, without looking down. Hold briefly, then relax.','Improve neck control and tolerance of a neutral posture.','Think of a small horizontal movement, not a forceful chin tuck.','Looking down, pushing hard, or provoking radiating pain.','Start with minimal range. Do not continue if the movement clearly increases dizziness or neurological symptoms.','Stop for sharp pain, clearly increased radiating pain, significant dizziness, double vision, new weakness, or numbness.','Modify after recent cervical surgery or when this movement is medically restricted.'),
('head-neck-cervical-retraction','de','Sanfte Halsretraktion','Kopfkontrolle und Halsausrichtung','Sitzen Sie an einer Lehne oder stehen Sie stabil, Blick horizontal.','Ziehen Sie das Kinn sehr leicht gerade nach hinten, als würde der Nacken länger, ohne nach unten zu schauen. Kurz halten, dann lösen.','Halskontrolle und Toleranz einer neutralen Haltung verbessern.','Kleine horizontale Bewegung statt kräftigem Doppelkinn.','Nach unten schauen, stark drücken oder Ausstrahlung provozieren.','Mit minimaler Bewegungsweite beginnen. Nicht fortsetzen, wenn Schwindel oder neurologische Symptome deutlich zunehmen.','Bei stechendem Schmerz, deutlich zunehmender Ausstrahlung, starkem Schwindel, Doppelbildern, neuer Schwäche oder Taubheit abbrechen.','Nach frischer Halsoperation oder bei medizinisch eingeschränkter Bewegung anpassen.'),

('head-neck-scapular-setting','fr','Placement doux des omoplates','Contrôle scapulaire et posture du haut du dos','Assis ou debout, bras détendus et épaules relâchées.','Ramenez très légèrement les omoplates vers une position neutre sans tirer fortement les épaules en arrière. Maintenez puis relâchez.','Améliorer le soutien postural du cou et du haut du dos.','Gardez les épaules basses et le cou détendu.','Pincer fortement les omoplates, hausser les épaules ou cambrer le dos.','L’effort doit rester léger et ne pas augmenter les symptômes cervicaux.','Arrêtez en cas de douleur vive, irradiation nouvelle, vertige important ou engourdissement/ faiblesse nouveaux.','À adapter si la position debout ou assise n’est pas bien tolérée.'),
('head-neck-scapular-setting','en','Gentle scapular setting','Scapular control and upper-back posture','Sit or stand with arms relaxed and shoulders loose.','Gently guide the shoulder blades toward a neutral position without forcefully pulling the shoulders back. Hold, then relax.','Improve postural support for the neck and upper back.','Keep the shoulders low and the neck relaxed.','Pinching the shoulder blades hard, shrugging, or over-arching the back.','Keep the effort light and do not increase neck symptoms.','Stop for sharp pain, new radiating symptoms, significant dizziness, or new numbness/weakness.','Modify if sitting or standing is poorly tolerated.'),
('head-neck-scapular-setting','de','Sanfte Schulterblatt-Einstellung','Schulterblattkontrolle und obere Rückenhaltung','Sitzen oder stehen Sie mit entspannten Armen und Schultern.','Führen Sie die Schulterblätter sehr leicht in eine neutrale Position, ohne die Schultern kräftig nach hinten zu ziehen. Halten, dann lösen.','Haltungsunterstützung für Nacken und oberen Rücken verbessern.','Schultern tief und Nacken entspannt halten.','Schulterblätter stark zusammenpressen, Schultern hochziehen oder Rücken überstrecken.','Belastung leicht halten und Nackensymptome nicht verstärken.','Bei stechendem Schmerz, neuer Ausstrahlung, starkem Schwindel oder neuer Taubheit/Schwäche abbrechen.','Anpassen, wenn Sitzen oder Stehen schlecht vertragen wird.'),

('head-neck-jaw-relaxation','fr','Relâchement et ouverture douce de la mâchoire','Contrôle de l’ATM et détente mandibulaire','Assis confortablement, langue reposant doucement au palais derrière les dents supérieures, dents non serrées.','Laissez la mâchoire se détendre puis ouvrez légèrement la bouche dans une amplitude confortable avant de refermer sans serrer.','Favoriser une ouverture contrôlée et réduire les tensions de serrage.','Les dents ne doivent pas rester serrées entre les répétitions.','Ouvrir trop grand, forcer malgré un blocage ou serrer la mâchoire.','Le mouvement doit rester doux. Une mâchoire bloquée, un traumatisme récent ou un gonflement important nécessite une évaluation.','Arrêtez en cas de douleur vive, blocage, déviation brutale inhabituelle, gonflement marqué ou aggravation nette des symptômes.','À éviter ou adapter après traumatisme récent, chirurgie de l’ATM ou en cas de blocage mandibulaire non évalué.'),
('head-neck-jaw-relaxation','en','Jaw relaxation and gentle opening','TMJ control and jaw relaxation','Sit comfortably with the tongue resting gently on the palate behind the upper teeth and the teeth unclenched.','Let the jaw relax, then gently open the mouth through a comfortable range and close without clenching.','Support controlled opening and reduce clenching-related tension.','Keep the teeth apart between repetitions.','Opening too wide, forcing through locking, or clenching the jaw.','Keep the movement gentle. A locked jaw, recent trauma, or marked swelling requires assessment.','Stop for sharp pain, locking, an unusual sudden deviation, marked swelling, or clear worsening of symptoms.','Avoid or modify after recent trauma, TMJ surgery, or with an unassessed locked jaw.'),
('head-neck-jaw-relaxation','de','Kieferentspannung und sanftes Öffnen','Kiefergelenkskontrolle und Entspannung','Sitzen Sie bequem, Zunge sanft am Gaumen hinter den oberen Zähnen, Zähne nicht zusammengepresst.','Lassen Sie den Kiefer locker und öffnen Sie den Mund sanft in angenehmer Weite, dann schließen ohne zu pressen.','Kontrollierte Öffnung unterstützen und Pressspannung reduzieren.','Zähne zwischen den Wiederholungen nicht zusammenpressen.','Zu weit öffnen, trotz Blockierung erzwingen oder Kiefer zusammenpressen.','Bewegung sanft halten. Ein blockierter Kiefer, frisches Trauma oder deutliche Schwellung muss abgeklärt werden.','Bei stechendem Schmerz, Blockierung, plötzlich ungewöhnlicher Abweichung, deutlicher Schwellung oder klarer Verschlechterung abbrechen.','Nach frischem Trauma, Kiefergelenk-Operation oder bei nicht abgeklärter Kieferblockierung vermeiden oder anpassen.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set
  name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,
  why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,
  safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'head-neck',true from public.exercises
where stable_key in ('head-neck-breathing-relaxation','head-neck-gentle-rotation','head-neck-cervical-retraction','head-neck-scapular-setting','head-neck-jaw-relaxation')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('head-neck-gentle-rotation','micro-range','easy',0,2,4,null,20,'slow-controlled'),
('head-neck-gentle-rotation','comfortable-range','standard',1,2,6,null,20,'slow-controlled'),
('head-neck-gentle-rotation','slightly-larger-range','hard',2,3,6,null,30,'slow-controlled'),
('head-neck-cervical-retraction','supported-retraction','easy',0,3,6,2,30,'controlled'),
('head-neck-cervical-retraction','standard-retraction','standard',1,3,8,3,30,'controlled'),
('head-neck-cervical-retraction','longer-hold-retraction','hard',2,3,8,5,45,'controlled')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set
  difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,
  sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,
  hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,
  tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('head-neck-gentle-rotation','micro-range','fr','Rotation très petite amplitude','Tournez la tête de quelques degrés seulement, lentement et sans provoquer de vertige.','Utilisez cette variante si le cou ou l’équilibre est sensible.'),
('head-neck-gentle-rotation','micro-range','en','Very small-range rotation','Turn the head only a few degrees, slowly and without provoking dizziness.','Use this option if the neck or balance is sensitive.'),
('head-neck-gentle-rotation','micro-range','de','Sehr kleine Halsrotation','Kopf nur wenige Grad langsam drehen, ohne Schwindel zu provozieren.','Bei empfindlichem Nacken oder Gleichgewicht wählen.'),
('head-neck-gentle-rotation','comfortable-range','fr','Rotation amplitude confortable','Tournez lentement dans l’amplitude qui reste confortable et stable.','Ne cherchez pas la fin d’amplitude.'),
('head-neck-gentle-rotation','comfortable-range','en','Comfortable-range rotation','Turn slowly through the range that remains comfortable and stable.','Do not seek end range.'),
('head-neck-gentle-rotation','comfortable-range','de','Halsrotation angenehme Weite','Langsam in dem Bereich drehen, der angenehm und stabil bleibt.','Nicht die Endstellung anstreben.'),
('head-neck-gentle-rotation','slightly-larger-range','fr','Rotation amplitude légèrement augmentée','Augmentez légèrement l’amplitude seulement si la version standard reste bien tolérée.','L’amplitude augmente avant la vitesse.'),
('head-neck-gentle-rotation','slightly-larger-range','en','Slightly larger-range rotation','Increase the range slightly only if the standard version remains well tolerated.','Increase range before speed.'),
('head-neck-gentle-rotation','slightly-larger-range','de','Halsrotation etwas größere Weite','Bewegungsweite nur leicht erhöhen, wenn die Standardvariante gut vertragen wird.','Zuerst Weite, nicht Geschwindigkeit steigern.'),
('head-neck-cervical-retraction','supported-retraction','fr','Rétraction cervicale avec dossier','Effectuez le petit recul du menton avec le dos soutenu par un dossier.','Le dossier aide à limiter les compensations.'),
('head-neck-cervical-retraction','supported-retraction','en','Supported cervical retraction','Perform the small chin-back movement with the back supported by a chair.','The support helps limit compensation.'),
('head-neck-cervical-retraction','supported-retraction','de','Halsretraktion mit Lehne','Kinn leicht nach hinten ziehen, während der Rücken an einer Lehne gestützt ist.','Die Lehne hilft Ausweichbewegungen zu begrenzen.'),
('head-neck-cervical-retraction','standard-retraction','fr','Rétraction cervicale standard','Reculez légèrement le menton, maintenez brièvement puis relâchez.','Gardez le regard horizontal.'),
('head-neck-cervical-retraction','standard-retraction','en','Standard cervical retraction','Gently draw the chin back, hold briefly, then relax.','Keep the eyes level.'),
('head-neck-cervical-retraction','standard-retraction','de','Standard-Halsretraktion','Kinn sanft nach hinten ziehen, kurz halten und lösen.','Blick horizontal halten.'),
('head-neck-cervical-retraction','longer-hold-retraction','fr','Rétraction avec maintien prolongé','Gardez la même petite amplitude mais maintenez un peu plus longtemps.','Augmentez la durée sans augmenter la force.'),
('head-neck-cervical-retraction','longer-hold-retraction','en','Cervical retraction with longer hold','Keep the same small range but hold a little longer.','Increase duration without increasing force.'),
('head-neck-cervical-retraction','longer-hold-retraction','de','Halsretraktion mit längerem Halten','Gleiche kleine Bewegung etwas länger halten.','Dauer erhöhen, nicht Kraft.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;