insert into public.exercises (stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable) values
('posture-ergonomics-breathing-reset','draft','1.0.0',2,6,5,20,5,'slow-controlled',false),
('posture-ergonomics-thoracic-extension','draft','1.0.0',2,8,0,30,4,'slow-controlled',false),
('posture-ergonomics-scapular-setting','draft','1.0.0',3,8,5,30,4,'isometric',false),
('posture-ergonomics-sit-to-stand','draft','1.0.0',3,8,0,45,3,'controlled',false),
('posture-ergonomics-standing-break','draft','1.0.0',2,8,0,20,5,'controlled',false)
on conflict (stable_key) do update set status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,default_tempo=excluded.default_tempo;

insert into public.exercise_translations (exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e join (values
('posture-ergonomics-breathing-reset','fr','Reset respiratoire postural','Respiration et relâchement postural','Assis ou debout confortablement.','Respirez lentement, relâchez les épaules et revenez vers une position confortable sans vous raidir.','Interrompre les postures prolongées et réduire la tension inutile.','Cherchez une posture confortable, pas une posture parfaite.','Se raidir, bloquer la respiration ou forcer le dos droit.','Restez dans une position stable et confortable.','Arrêtez en cas de douleur vive, malaise, faiblesse ou engourdissement nouveaux.','À adapter si la station assise ou debout est mal tolérée.'),
('posture-ergonomics-breathing-reset','en','Postural breathing reset','Breathing and postural relaxation','Sit or stand comfortably.','Breathe slowly, relax the shoulders, and return toward a comfortable position without stiffening.','Break up prolonged postures and reduce unnecessary tension.','Aim for comfort, not a perfect posture.','Stiffening, holding the breath, or forcing an upright position.','Stay stable and comfortable.','Stop for sharp pain, faintness, new weakness, or numbness.','Modify if sitting or standing is poorly tolerated.'),
('posture-ergonomics-breathing-reset','de','Haltungs-Reset mit Atmung','Atmung und Haltungsentspannung','Bequem sitzen oder stehen.','Langsam atmen, Schultern entspannen und ohne Versteifung in eine angenehme Position zurückkehren.','Lange statische Haltungen unterbrechen und unnötige Spannung reduzieren.','Komfort statt perfekter Haltung.','Versteifen, Luft anhalten oder sich gewaltsam aufrichten.','Stabil und angenehm bleiben.','Bei stechendem Schmerz, Kreislaufproblemen, neuer Schwäche oder Taubheit abbrechen.','Bei schlecht toleriertem Sitzen oder Stehen anpassen.'),
('posture-ergonomics-thoracic-extension','fr','Extension thoracique douce','Mobilité du haut du dos','Assis sur une chaise stable.','Redressez doucement le haut du dos au-dessus du dossier sans forcer la nuque.','Entretenir la mobilité thoracique utile aux postures de travail.','Le mouvement vient du haut du dos.','Cambrer fortement le bas du dos ou tirer sur la nuque.','Amplitude petite et confortable.','Arrêtez en cas de douleur vive, vertige ou irradiation nouvelle.','À adapter si l’extension thoracique est médicalement limitée.'),
('posture-ergonomics-thoracic-extension','en','Gentle thoracic extension','Upper-back mobility','Sit on a stable chair.','Gently extend the upper back over the chair without forcing the neck.','Maintain thoracic mobility useful for work postures.','Move through the upper back.','Over-arching the lower back or pulling on the neck.','Use a small comfortable range.','Stop for sharp pain, dizziness, or new radiating symptoms.','Modify if thoracic extension is medically restricted.'),
('posture-ergonomics-thoracic-extension','de','Sanfte Brustwirbelsäulenstreckung','Beweglichkeit des oberen Rückens','Auf stabilem Stuhl sitzen.','Oberen Rücken sanft über der Lehne strecken, ohne den Nacken zu erzwingen.','Brustwirbelsäulenbeweglichkeit für Arbeitshaltungen erhalten.','Bewegung aus dem oberen Rücken.','Lendenwirbelsäule stark überstrecken oder am Nacken ziehen.','Kleine angenehme Bewegungsweite.','Bei stechendem Schmerz, Schwindel oder neuer Ausstrahlung abbrechen.','Bei medizinisch eingeschränkter Streckung anpassen.'),
('posture-ergonomics-scapular-setting','fr','Placement doux des omoplates','Contrôle scapulaire','Assis ou debout, bras relâchés.','Amenez doucement les omoplates vers une position neutre, maintenez puis relâchez.','Améliorer le contrôle du haut du dos sans rigidifier la posture.','Gardez le cou détendu.','Pincer fortement les omoplates ou hausser les épaules.','Effort léger uniquement.','Arrêtez en cas de douleur vive ou symptômes neurologiques nouveaux.','À adapter si les épaules sont douloureuses ou récemment opérées.'),
('posture-ergonomics-scapular-setting','en','Gentle scapular setting','Scapular control','Sit or stand with arms relaxed.','Gently guide the shoulder blades toward neutral, hold, then relax.','Improve upper-back control without rigid posture.','Keep the neck relaxed.','Pinching hard or shrugging.','Use only light effort.','Stop for sharp pain or new neurological symptoms.','Modify for painful or recently operated shoulders.'),
('posture-ergonomics-scapular-setting','de','Sanfte Schulterblatt-Einstellung','Schulterblattkontrolle','Sitzen oder stehen, Arme entspannt.','Schulterblätter sanft in Neutralstellung führen, halten, dann lösen.','Kontrolle des oberen Rückens ohne starre Haltung verbessern.','Nacken entspannt halten.','Stark zusammenpressen oder Schultern hochziehen.','Nur leichte Anspannung.','Bei stechendem Schmerz oder neuen neurologischen Symptomen abbrechen.','Bei schmerzhaften oder frisch operierten Schultern anpassen.'),
('posture-ergonomics-sit-to-stand','fr','Assis-debout contrôlé','Force fonctionnelle et changement de posture','Assis sur une chaise stable, pieds au sol.','Penchez légèrement le tronc, poussez dans les pieds pour vous lever puis asseyez-vous avec contrôle.','Renforcer les jambes et interrompre la sédentarité prolongée.','Utilisez les accoudoirs si nécessaire.','Se laisser tomber sur la chaise ou se lever trop vite.','Chaise stable et environnement dégagé.','Arrêtez en cas de vertige, douleur vive ou perte d’équilibre.','À adapter si l’appui ou les transferts sont limités médicalement.'),
('posture-ergonomics-sit-to-stand','en','Controlled sit-to-stand','Functional strength and posture change','Sit on a stable chair with feet supported.','Lean slightly forward, push through the feet to stand, then sit down with control.','Build leg strength and break up prolonged sitting.','Use armrests if needed.','Dropping into the chair or standing too quickly.','Use a stable chair and clear space.','Stop for dizziness, sharp pain, or loss of balance.','Modify if weight bearing or transfers are medically restricted.'),
('posture-ergonomics-sit-to-stand','de','Kontrolliertes Aufstehen und Hinsetzen','Funktionelle Kraft und Positionswechsel','Auf stabilem Stuhl sitzen, Füße am Boden.','Oberkörper leicht vor, über die Füße aufstehen und kontrolliert wieder hinsetzen.','Beinkraft aufbauen und langes Sitzen unterbrechen.','Bei Bedarf Armlehnen nutzen.','Auf den Stuhl fallen lassen oder zu schnell aufstehen.','Stabilen Stuhl und freien Raum nutzen.','Bei Schwindel, stechendem Schmerz oder Gleichgewichtsverlust abbrechen.','Bei eingeschränkter Belastung oder Transfers anpassen.'),
('posture-ergonomics-standing-break','fr','Pause active debout','Mobilité générale et rupture de sédentarité','Debout près d’un support stable.','Alternez doucement transfert de poids, petits pas sur place et relâchement des épaules.','Créer une micro-pause active simple au travail ou en télétravail.','Bougez régulièrement plutôt que longtemps.','Faire de grands mouvements ou perdre l’équilibre.','Utilisez un support si nécessaire.','Arrêtez en cas de vertige, essoufflement inhabituel ou douleur vive.','À adapter si la station debout n’est pas sûre.'),
('posture-ergonomics-standing-break','en','Active standing break','General mobility and breaking sedentary time','Stand near stable support.','Gently alternate weight shifts, small steps in place, and shoulder relaxation.','Create a simple active micro-break at work or home.','Move regularly rather than for long periods.','Using large movements or losing balance.','Use support if needed.','Stop for dizziness, unusual shortness of breath, or sharp pain.','Modify if standing is unsafe.'),
('posture-ergonomics-standing-break','de','Aktive Stehpause','Allgemeine Mobilität und Unterbrechung langen Sitzens','Nahe einer stabilen Stütze stehen.','Sanfte Gewichtsverlagerungen, kleine Schritte am Platz und Schulterentspannung abwechseln.','Einfache aktive Mikropause bei Arbeit oder Homeoffice schaffen.','Regelmäßig statt lange bewegen.','Zu große Bewegungen oder Gleichgewichtsverlust.','Bei Bedarf Stütze nutzen.','Bei Schwindel, ungewöhnlicher Atemnot oder stechendem Schmerz abbrechen.','Bei unsicherem Stand anpassen.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications) on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'spine-back',true from public.exercises where stable_key in ('posture-ergonomics-breathing-reset','posture-ergonomics-thoracic-extension','posture-ergonomics-scapular-setting','posture-ergonomics-sit-to-stand','posture-ergonomics-standing-break')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override from public.exercises e join (values
('posture-ergonomics-sit-to-stand','high-chair-arms','easy',0,2,6,null::integer,45,'controlled'),
('posture-ergonomics-sit-to-stand','standard-chair','standard',1,3,8,null::integer,45,'controlled'),
('posture-ergonomics-sit-to-stand','slow-lowering','hard',2,3,8,null::integer,60,'3-second-lowering'),
('posture-ergonomics-standing-break','supported','easy',0,2,6,null::integer,20,'controlled'),
('posture-ergonomics-standing-break','standard','standard',1,2,8,null::integer,20,'controlled'),
('posture-ergonomics-standing-break','longer-break','hard',2,3,8,null::integer,30,'controlled')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override) on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip from public.exercise_variants ev join public.exercises e on e.id=ev.exercise_id join (values
('posture-ergonomics-sit-to-stand','high-chair-arms','fr','Chaise haute avec appui','Utilisez une chaise plus haute et les accoudoirs si nécessaire.','Priorité à la sécurité.'),('posture-ergonomics-sit-to-stand','high-chair-arms','en','High chair with arm support','Use a higher chair and armrests if needed.','Prioritise safety.'),('posture-ergonomics-sit-to-stand','high-chair-arms','de','Hoher Stuhl mit Armstütze','Höheren Stuhl und bei Bedarf Armlehnen nutzen.','Sicherheit zuerst.'),
('posture-ergonomics-sit-to-stand','standard-chair','fr','Assis-debout standard','Levez-vous d’une chaise stable sans vitesse excessive.','Gardez les pieds bien posés.'),('posture-ergonomics-sit-to-stand','standard-chair','en','Standard sit-to-stand','Stand from a stable chair without rushing.','Keep the feet well supported.'),('posture-ergonomics-sit-to-stand','standard-chair','de','Standard Aufstehen','Von stabilem Stuhl ohne Hast aufstehen.','Füße gut aufstellen.'),
('posture-ergonomics-sit-to-stand','slow-lowering','fr','Descente lente','Asseyez-vous en environ trois secondes.','Contrôlez la descente.'),('posture-ergonomics-sit-to-stand','slow-lowering','en','Slow lowering','Sit down over about three seconds.','Control the descent.'),('posture-ergonomics-sit-to-stand','slow-lowering','de','Langsames Hinsetzen','Über etwa drei Sekunden hinsetzen.','Absenken kontrollieren.'),
('posture-ergonomics-standing-break','supported','fr','Pause avec appui','Gardez une main près d’un support stable.','Petits mouvements.'),('posture-ergonomics-standing-break','supported','en','Supported break','Keep one hand near stable support.','Use small movements.'),('posture-ergonomics-standing-break','supported','de','Pause mit Stütze','Eine Hand nahe einer stabilen Stütze halten.','Kleine Bewegungen.'),
('posture-ergonomics-standing-break','standard','fr','Pause active standard','Alternez transferts et petits pas confortables.','Restez fluide.'),('posture-ergonomics-standing-break','standard','en','Standard active break','Alternate comfortable shifts and small steps.','Keep it smooth.'),('posture-ergonomics-standing-break','standard','de','Standard aktive Pause','Angenehme Gewichtsverlagerungen und kleine Schritte abwechseln.','Flüssig bleiben.'),
('posture-ergonomics-standing-break','longer-break','fr','Pause active prolongée','Prolongez légèrement la durée si bien toléré.','Augmentez la durée, pas l’intensité.'),('posture-ergonomics-standing-break','longer-break','en','Longer active break','Extend the duration slightly if well tolerated.','Increase duration, not intensity.'),('posture-ergonomics-standing-break','longer-break','de','Längere aktive Pause','Dauer bei guter Verträglichkeit leicht verlängern.','Dauer statt Intensität steigern.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip) on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;