insert into public.exercises (stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable) values
('knee-quadriceps-isometric','draft','1.0.0',3,10,5,30,5,'isometric',false),
('knee-heel-slide','draft','1.0.0',3,10,0,30,5,'slow-controlled',false),
('knee-straight-leg-raise','draft','1.0.0',3,10,0,45,4,'slow-controlled',false),
('knee-sit-to-stand','draft','1.0.0',3,8,0,60,3,'controlled',false),
('knee-low-step-up','draft','1.0.0',3,8,0,60,3,'controlled',false)
on conflict (stable_key) do update set status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,default_tempo=excluded.default_tempo;

insert into public.exercise_translations (exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('knee-quadriceps-isometric','fr','Contraction isométrique du quadriceps','Quadriceps et contrôle de l’extension du genou','Allongé ou assis, jambe soutenue et genou dans une position confortable.','Contractez doucement la cuisse en cherchant à tendre le genou sans décoller toute la jambe. Maintenez puis relâchez.','Entretenir l’activation du quadriceps et le contrôle du genou.','Contractez fermement mais sans bloquer votre respiration.','Soulever la hanche, retenir sa respiration ou forcer dans une amplitude douloureuse.','Effectuez le mouvement de façon confortable et contrôlée. En cas d’opération récente, respectez les consignes de votre équipe soignante.','Arrêtez en cas de douleur vive, gonflement qui augmente nettement, sensation d’instabilité inhabituelle, malaise ou autre symptôme inquiétant.','À ne pas utiliser comme exercice autonome en présence d’une restriction médicale ou post-opératoire non clarifiée.'),
('knee-quadriceps-isometric','en','Quadriceps isometric contraction','Quadriceps activation and knee extension control','Lie or sit with the leg supported and the knee in a comfortable position.','Gently tighten the thigh as if straightening the knee without lifting the whole leg. Hold, then relax.','Maintain quadriceps activation and knee control.','Contract firmly without holding your breath.','Lifting the hip, holding the breath, or forcing into a painful position.','Keep the effort comfortable and controlled. After recent surgery, follow the instructions of your treating team.','Stop for sharp pain, a marked increase in swelling, unusual giving-way, dizziness, or any other concerning symptom.','Not for unsupervised use when a medical or post-operative restriction has not been clarified.'),
('knee-quadriceps-isometric','de','Isometrische Quadrizeps-Anspannung','Quadrizepsaktivierung und Kontrolle der Kniestreckung','Liegen oder sitzen Sie mit unterstütztem Bein und bequem gelagertem Knie.','Spannen Sie den Oberschenkel sanft an, als wollten Sie das Knie strecken, ohne das ganze Bein anzuheben. Halten, dann lösen.','Quadrizepsaktivierung und Kniekontrolle erhalten.','Kräftig anspannen, ohne die Luft anzuhalten.','Becken anheben, Luft anhalten oder in eine schmerzhafte Position drücken.','Führen Sie die Anspannung angenehm und kontrolliert aus. Nach einer frischen Operation gelten die Vorgaben des Behandlungsteams.','Bei stechendem Schmerz, deutlich zunehmender Schwellung, ungewöhnlichem Wegknicken, Schwindel oder anderen bedenklichen Symptomen abbrechen.','Nicht als selbstständige Übung verwenden, wenn medizinische oder postoperative Einschränkungen ungeklärt sind.'),
('knee-heel-slide','fr','Glissement du talon','Mobilité contrôlée en flexion et extension du genou','Allongé sur le dos, jambe détendue, talon posé sur une surface permettant de glisser.','Faites glisser lentement le talon vers les fesses pour plier le genou, puis revenez progressivement vers la position de départ.','Entretenir ou récupérer progressivement la mobilité du genou.','Restez dans une amplitude confortable et régulière.','Forcer la flexion, décoller le talon inutilement ou faire des mouvements rapides.','Le mouvement doit rester doux. Après une chirurgie, ne dépassez pas les limites indiquées par votre équipe soignante.','Arrêtez en cas de douleur vive, blocage, gonflement qui augmente nettement ou autre réaction inhabituelle.','À adapter ou éviter si une limitation d’amplitude a été prescrite.'),
('knee-heel-slide','en','Heel slide','Controlled knee flexion and extension mobility','Lie on your back with the leg relaxed and the heel on a surface that allows it to slide.','Slowly slide the heel toward the buttocks to bend the knee, then gradually return to the starting position.','Maintain or gradually restore knee mobility.','Stay within a comfortable, smooth range.','Forcing the bend, unnecessarily lifting the heel, or moving quickly.','Keep the movement gentle. After surgery, do not exceed range limits given by your treating team.','Stop for sharp pain, locking, a marked increase in swelling, or another unusual reaction.','Modify or avoid if a specific range-of-motion restriction has been prescribed.'),
('knee-heel-slide','de','Fersengleiten','Kontrollierte Beuge- und Streckbeweglichkeit des Knies','Legen Sie sich auf den Rücken, das Bein entspannt, die Ferse auf einer gleitfähigen Unterlage.','Ziehen Sie die Ferse langsam zum Gesäß, um das Knie zu beugen, und gleiten Sie anschließend kontrolliert zurück.','Kniefunktion erhalten oder Beweglichkeit schrittweise wiedererlangen.','Bleiben Sie in einem angenehmen und gleichmäßigen Bewegungsumfang.','Beugung erzwingen, Ferse unnötig anheben oder zu schnell bewegen.','Die Bewegung soll sanft bleiben. Nach einer Operation gelten die Bewegungsgrenzen des Behandlungsteams.','Bei stechendem Schmerz, Blockieren, deutlich zunehmender Schwellung oder anderer ungewöhnlicher Reaktion abbrechen.','Bei verordneter Bewegungslimitierung anpassen oder vermeiden.'),
('knee-straight-leg-raise','fr','Élévation de jambe tendue','Quadriceps et contrôle du membre inférieur','Allongé sur le dos, une jambe pliée si confortable, l’autre tendue.','Contractez la cuisse de la jambe tendue puis soulevez-la lentement de quelques centimètres, gardez le genou stable et redescendez avec contrôle.','Renforcer le contrôle actif du genou et de la cuisse.','Gardez le genou aussi stable que possible pendant tout le mouvement.','Lever trop haut, cambrer fortement le dos ou laisser le genou se plier.','Travaillez lentement et sans forcer. Si vous ne pouvez pas maintenir le genou stable, utilisez une variante plus facile.','Arrêtez en cas de douleur vive, faiblesse brutale, gonflement nettement accru ou autre symptôme inquiétant.','Peut être inadapté en phase post-opératoire précoce ou si l’élévation active de la jambe est restreinte.'),
('knee-straight-leg-raise','en','Straight leg raise','Quadriceps and lower-limb control','Lie on your back with one knee bent if comfortable and the other leg straight.','Tighten the thigh of the straight leg, slowly lift it a short distance, keep the knee stable, and lower with control.','Build active control of the knee and thigh.','Keep the knee as steady as possible throughout the movement.','Lifting too high, strongly arching the back, or letting the knee bend.','Move slowly without forcing. If the knee cannot remain stable, use an easier variation.','Stop for sharp pain, sudden weakness, a marked increase in swelling, or another concerning symptom.','May be unsuitable in an early post-operative phase or when active straight-leg lifting is restricted.'),
('knee-straight-leg-raise','de','Gestrecktes Beinheben','Quadrizeps und Kontrolle der unteren Extremität','Legen Sie sich auf den Rücken; ein Bein kann bequem angestellt sein, das andere bleibt gestreckt.','Spannen Sie den Oberschenkel des gestreckten Beins an, heben Sie das Bein langsam etwas an, halten Sie das Knie stabil und senken Sie kontrolliert ab.','Aktive Kontrolle von Knie und Oberschenkel aufbauen.','Das Knie während der gesamten Bewegung möglichst stabil halten.','Zu hoch anheben, den Rücken stark ins Hohlkreuz bringen oder das Knie beugen lassen.','Langsam und ohne Zwang arbeiten. Wenn das Knie nicht stabil bleibt, eine leichtere Variante wählen.','Bei stechendem Schmerz, plötzlicher Schwäche, deutlich zunehmender Schwellung oder anderen bedenklichen Symptomen abbrechen.','Kann in einer frühen postoperativen Phase oder bei Einschränkung des aktiven Beinhebens ungeeignet sein.'),
('knee-sit-to-stand','fr','Assis-debout contrôlé','Force fonctionnelle des jambes et contrôle du transfert','Assis sur une chaise stable, pieds posés au sol, légèrement écartés.','Inclinez légèrement le tronc vers l’avant, poussez dans les pieds pour vous lever, stabilisez-vous, puis rassoyez-vous lentement.','Améliorer la force fonctionnelle nécessaire pour se lever et s’asseoir au quotidien.','Gardez les genoux orientés dans la même direction que les pieds.','Se laisser tomber sur la chaise, rapprocher excessivement les genoux ou prendre de l’élan.','Utilisez une chaise stable et un support proche si votre équilibre est incertain.','Arrêtez en cas de douleur vive, vertige, perte d’équilibre ou sensation d’instabilité importante.','À réaliser avec assistance ou à éviter si le transfert assis-debout n’est pas sûr de façon autonome.'),
('knee-sit-to-stand','en','Controlled sit-to-stand','Functional leg strength and transfer control','Sit on a stable chair with feet on the floor, slightly apart.','Lean the trunk slightly forward, push through the feet to stand, steady yourself, then sit down slowly.','Improve functional strength for everyday standing up and sitting down.','Keep the knees pointing in the same direction as the feet.','Dropping onto the chair, letting the knees collapse inward, or using excessive momentum.','Use a stable chair and keep a support nearby if balance is uncertain.','Stop for sharp pain, dizziness, loss of balance, or marked instability.','Use assistance or avoid unsupervised practice if sit-to-stand transfers are not safe independently.'),
('knee-sit-to-stand','de','Kontrolliertes Aufstehen und Hinsetzen','Funktionelle Beinkraft und Transferkontrolle','Sitzen Sie auf einem stabilen Stuhl, die Füße stehen leicht auseinander auf dem Boden.','Neigen Sie den Oberkörper leicht nach vorn, drücken Sie über die Füße zum Stand, stabilisieren Sie sich und setzen Sie sich langsam wieder hin.','Funktionelle Kraft für alltägliches Aufstehen und Hinsetzen verbessern.','Knie in Richtung der Füße führen.','Auf den Stuhl fallen lassen, Knie stark nach innen kippen oder übermäßig Schwung holen.','Verwenden Sie einen stabilen Stuhl und halten Sie bei unsicherem Gleichgewicht eine Stützmöglichkeit bereit.','Bei stechendem Schmerz, Schwindel, Gleichgewichtsverlust oder deutlicher Instabilität abbrechen.','Mit Unterstützung durchführen oder nicht allein üben, wenn der Transfer nicht sicher selbstständig möglich ist.'),
('knee-low-step-up','fr','Montée sur marche basse','Force fonctionnelle du genou et contrôle de la montée','Debout devant une marche basse et stable, avec un support à proximité si nécessaire.','Posez un pied sur la marche, poussez progressivement pour monter, contrôlez l’alignement du genou, puis redescendez lentement.','Préparer les activités comme les escaliers et renforcer le contrôle fonctionnel du membre inférieur.','Montez avec contrôle plutôt qu’avec élan.','Genou qui s’effondre vers l’intérieur, impulsion excessive ou descente non contrôlée.','Commencez avec une marche basse et utilisez un support si l’équilibre est incertain.','Arrêtez en cas de douleur vive, instabilité, vertige, blocage ou gonflement nettement accru.','À éviter sans supervision si les escaliers ou la mise en charge sur une jambe ne sont pas sûrs.'),
('knee-low-step-up','en','Low step-up','Functional knee strength and step control','Stand in front of a low, stable step with support nearby if needed.','Place one foot on the step, gradually push up, control knee alignment, then step down slowly.','Prepare for stair activities and improve functional lower-limb control.','Step up with control rather than momentum.','Knee collapsing inward, excessive push-off, or uncontrolled lowering.','Start with a low step and use support if balance is uncertain.','Stop for sharp pain, instability, dizziness, locking, or a marked increase in swelling.','Avoid unsupervised practice if stairs or single-leg loading are not safe.'),
('knee-low-step-up','de','Aufsteigen auf eine niedrige Stufe','Funktionelle Kniekraft und Stufenkontrolle','Stehen Sie vor einer niedrigen stabilen Stufe; bei Bedarf befindet sich eine Stütze in der Nähe.','Setzen Sie einen Fuß auf die Stufe, drücken Sie sich kontrolliert nach oben, achten Sie auf die Knieachse und steigen Sie langsam wieder ab.','Treppenaktivitäten vorbereiten und die funktionelle Kontrolle des Beins verbessern.','Kontrolliert aufsteigen statt Schwung zu nutzen.','Knie nach innen kippen lassen, zu stark abstoßen oder unkontrolliert absteigen.','Mit einer niedrigen Stufe beginnen und bei unsicherem Gleichgewicht eine Stütze verwenden.','Bei stechendem Schmerz, Instabilität, Schwindel, Blockieren oder deutlich zunehmender Schwellung abbrechen.','Nicht allein durchführen, wenn Treppensteigen oder einbeinige Belastung nicht sicher möglich sind.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'knee-thigh',true from public.exercises where stable_key in ('knee-quadriceps-isometric','knee-heel-slide','knee-straight-leg-raise','knee-sit-to-stand','knee-low-step-up')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('knee-sit-to-stand','raised-seat-with-support','easy',0,3,6,null::integer,60,'controlled'),
('knee-sit-to-stand','standard-chair','standard',1,3,8,null::integer,60,'controlled'),
('knee-sit-to-stand','slow-lowering','hard',2,3,8,null::integer,75,'3-second-lowering'),
('knee-low-step-up','low-step-with-support','easy',0,3,6,null::integer,60,'controlled'),
('knee-low-step-up','low-step-standard','standard',1,3,8,null::integer,60,'controlled'),
('knee-low-step-up','higher-step-controlled','hard',2,3,8,null::integer,75,'controlled')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('knee-sit-to-stand','raised-seat-with-support','fr','Assis-debout depuis une assise haute avec appui','Utilisez une assise plus haute et, si nécessaire, les mains ou un support stable.','Réduisez l’aide progressivement lorsque le mouvement devient sûr.'),
('knee-sit-to-stand','raised-seat-with-support','en','Sit-to-stand from a raised seat with support','Use a higher seat and, if needed, the hands or a stable support.','Gradually reduce assistance once the movement is safe.'),
('knee-sit-to-stand','raised-seat-with-support','de','Aufstehen von erhöhter Sitzfläche mit Unterstützung','Nutzen Sie eine höhere Sitzfläche und bei Bedarf die Hände oder eine stabile Stütze.','Unterstützung schrittweise reduzieren, sobald die Bewegung sicher ist.'),
('knee-sit-to-stand','standard-chair','fr','Assis-debout depuis une chaise standard','Levez-vous et rassoyez-vous depuis une chaise stable sans précipitation.','Gardez un mouvement régulier et symétrique.'),
('knee-sit-to-stand','standard-chair','en','Sit-to-stand from a standard chair','Stand up and sit down from a stable chair without rushing.','Keep the movement smooth and symmetrical.'),
('knee-sit-to-stand','standard-chair','de','Aufstehen von einem normalen Stuhl','Stehen Sie von einem stabilen Stuhl auf und setzen Sie sich ohne Hast wieder hin.','Die Bewegung gleichmäßig und möglichst symmetrisch ausführen.'),
('knee-sit-to-stand','slow-lowering','fr','Assis-debout avec descente lente','Levez-vous normalement puis contrôlez la descente vers la chaise pendant environ trois secondes.','La difficulté vient du contrôle de la descente, pas de la vitesse.'),
('knee-sit-to-stand','slow-lowering','en','Sit-to-stand with slow lowering','Stand normally, then control the lowering back to the chair for about three seconds.','The challenge is controlled lowering, not speed.'),
('knee-sit-to-stand','slow-lowering','de','Aufstehen mit langsamem Hinsetzen','Stehen Sie normal auf und kontrollieren Sie das Hinsetzen über etwa drei Sekunden.','Die Schwierigkeit entsteht durch die kontrollierte Abwärtsphase, nicht durch Geschwindigkeit.'),
('knee-low-step-up','low-step-with-support','fr','Montée sur marche basse avec appui','Utilisez une marche très basse et un support stable pour l’équilibre.','Réduisez progressivement l’appui lorsque le contrôle s’améliore.'),
('knee-low-step-up','low-step-with-support','en','Low step-up with support','Use a very low step and a stable support for balance.','Gradually reduce support as control improves.'),
('knee-low-step-up','low-step-with-support','de','Aufsteigen auf niedrige Stufe mit Unterstützung','Nutzen Sie eine sehr niedrige Stufe und eine stabile Stütze für das Gleichgewicht.','Unterstützung schrittweise reduzieren, wenn die Kontrolle besser wird.'),
('knee-low-step-up','low-step-standard','fr','Montée sur marche basse standard','Montez et redescendez d’une marche basse avec un contrôle régulier.','Gardez le genou aligné avec le pied.'),
('knee-low-step-up','low-step-standard','en','Standard low step-up','Step up and down from a low step with steady control.','Keep the knee aligned with the foot.'),
('knee-low-step-up','low-step-standard','de','Standard-Aufsteigen auf niedrige Stufe','Steigen Sie kontrolliert auf eine niedrige Stufe und wieder herunter.','Knie in Richtung des Fußes führen.'),
('knee-low-step-up','higher-step-controlled','fr','Montée contrôlée sur marche plus haute','Utilisez une marche légèrement plus haute uniquement si la version standard est bien contrôlée.','Augmentez la hauteur, pas la vitesse.'),
('knee-low-step-up','higher-step-controlled','en','Controlled higher step-up','Use a slightly higher step only when the standard version is well controlled.','Increase height, not speed.'),
('knee-low-step-up','higher-step-controlled','de','Kontrolliertes Aufsteigen auf höhere Stufe','Nutzen Sie eine etwas höhere Stufe nur, wenn die Standardvariante sicher kontrolliert wird.','Erhöhen Sie die Stufenhöhe, nicht die Geschwindigkeit.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;

comment on table public.exercises is 'M02 reusable exercise content objects. M02.1 seeds a small knee pilot in DRAFT only; no exercise is clinically approved or publicly accessible yet.';
