insert into public.programme_phases (programme_id,stable_key,sort_order,status) values (9,'reset-mobility',0,'draft'),(9,'strength-workday',1,'draft') on conflict (programme_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status;
insert into public.programme_phase_translations (phase_id,language,name,objective)
select pp.id,v.language,v.name,v.objective from public.programme_phases pp join (values
('reset-mobility','fr','Phase 1 — Reset et mobilité','Interrompre les postures prolongées, retrouver du mouvement et réduire la rigidité inutile.'),('reset-mobility','en','Phase 1 — Reset and mobility','Break up prolonged postures, restore movement, and reduce unnecessary stiffness.'),('reset-mobility','de','Phase 1 — Reset und Beweglichkeit','Lange Haltungen unterbrechen, Bewegung fördern und unnötige Steifigkeit reduzieren.'),
('strength-workday','fr','Phase 2 — Force et journée active','Ajouter force fonctionnelle et micro-pauses pour mieux tolérer travail, télétravail ou conduite.'),('strength-workday','en','Phase 2 — Strength and active workday','Add functional strength and micro-breaks to better tolerate work, home office, or driving.'),('strength-workday','de','Phase 2 — Kraft und aktiver Arbeitstag','Funktionelle Kraft und Mikropausen für Arbeit, Homeoffice oder Fahren ergänzen.')
) v(phase_key,language,name,objective) on pp.programme_id=9 and pp.stable_key=v.phase_key on conflict (phase_id,language) do update set name=excluded.name,objective=excluded.objective;
insert into public.programme_sessions (phase_id,stable_key,sort_order,status,estimated_duration_minutes)
select pp.id,v.stable_key,v.sort_order,'draft',v.minutes from public.programme_phases pp join (values ('reset-mobility','session-reset-a',0,10),('reset-mobility','session-mobility-b',1,12),('strength-workday','session-strength-a',0,14),('strength-workday','session-workday-b',1,15)) v(phase_key,stable_key,sort_order,minutes) on pp.programme_id=9 and pp.stable_key=v.phase_key on conflict (phase_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status,estimated_duration_minutes=excluded.estimated_duration_minutes;
insert into public.programme_session_translations (session_id,language,name,intro,completion_message)
select ps.id,v.language,v.name,v.intro,v.done from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-reset-a','fr','Séance 1 — Reset postural','Respiration, relâchement et mobilité courte.','Terminé : changez régulièrement de position dans la journée.'),('session-reset-a','en','Session 1 — Postural reset','Breathing, relaxation, and short mobility work.','Complete: change position regularly during the day.'),('session-reset-a','de','Einheit 1 — Haltungs-Reset','Atmung, Entspannung und kurze Mobilität.','Fertig: Position im Tagesverlauf regelmäßig wechseln.'),
('session-mobility-b','fr','Séance 2 — Mobilité du haut du dos','Ajoutez mobilité thoracique et contrôle des omoplates.','Terminé : privilégiez la variété des positions.'),('session-mobility-b','en','Session 2 — Upper-back mobility','Add thoracic mobility and scapular control.','Complete: prioritise variety of positions.'),('session-mobility-b','de','Einheit 2 — Oberer Rücken','Brustwirbelsäulenbeweglichkeit und Schulterblattkontrolle ergänzen.','Fertig: Haltungsvielfalt bevorzugen.'),
('session-strength-a','fr','Séance 3 — Force fonctionnelle','Ajoutez assis-debout et pause active.','Terminé : gardez une charge confortable.'),('session-strength-a','en','Session 3 — Functional strength','Add sit-to-stand and an active break.','Complete: keep loading comfortable.'),('session-strength-a','de','Einheit 3 — Funktionelle Kraft','Aufstehen/Hinsetzen und aktive Pause ergänzen.','Fertig: Belastung angenehm halten.'),
('session-workday-b','fr','Séance 4 — Routine journée de travail','Combinez mobilité, contrôle et micro-pause active.','Terminé : répétez de petites pauses plutôt qu’une seule longue séance.'),('session-workday-b','en','Session 4 — Workday routine','Combine mobility, control, and an active micro-break.','Complete: repeat small breaks rather than one long session.'),('session-workday-b','de','Einheit 4 — Arbeitstagsroutine','Beweglichkeit, Kontrolle und aktive Mikropause kombinieren.','Fertig: mehrere kurze Pausen statt einer langen Einheit.')
) v(session_key,language,name,intro,done) on pp.programme_id=9 and ps.stable_key=v.session_key on conflict (session_id,language) do update set name=excluded.name,intro=excluded.intro,completion_message=excluded.completion_message;
insert into public.programme_session_exercises (session_id,exercise_id,exercise_variant_id,sort_order,is_optional,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select ps.id,e.id,ev.id,v.sort_order,false,v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-reset-a','posture-ergonomics-breathing-reset',null::text,0,2,6,5,20,'slow-controlled'),('session-reset-a','posture-ergonomics-thoracic-extension',null::text,1,2,6,null::integer,30,'slow-controlled'),('session-reset-a','posture-ergonomics-scapular-setting',null::text,2,2,8,5,30,'isometric'),
('session-mobility-b','posture-ergonomics-thoracic-extension',null::text,0,2,8,null::integer,30,'slow-controlled'),('session-mobility-b','posture-ergonomics-scapular-setting',null::text,1,3,8,5,30,'isometric'),('session-mobility-b','posture-ergonomics-standing-break','supported',2,2,6,null::integer,20,'controlled'),
('session-strength-a','posture-ergonomics-thoracic-extension',null::text,0,2,8,null::integer,30,'slow-controlled'),('session-strength-a','posture-ergonomics-sit-to-stand','high-chair-arms',1,3,6,null::integer,45,'controlled'),('session-strength-a','posture-ergonomics-standing-break','standard',2,2,8,null::integer,20,'controlled'),
('session-workday-b','posture-ergonomics-scapular-setting',null::text,0,3,8,5,30,'isometric'),('session-workday-b','posture-ergonomics-sit-to-stand','standard-chair',1,3,8,null::integer,45,'controlled'),('session-workday-b','posture-ergonomics-standing-break','longer-break',2,3,8,null::integer,30,'controlled')) v(session_key,exercise_key,variant_key,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on pp.programme_id=9 and ps.stable_key=v.session_key join public.exercises e on e.stable_key=v.exercise_key left join public.exercise_variants ev on ev.exercise_id=e.id and ev.stable_key=v.variant_key
on conflict (session_id,sort_order) do update set exercise_id=excluded.exercise_id,exercise_variant_id=excluded.exercise_variant_id,is_optional=excluded.is_optional,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;