insert into public.exercises (
  stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable
) values
('wrist-hand-active-mobility','draft','1.0.0',2,10,0,20,5,'slow-controlled',false),
('wrist-hand-tendon-glide','draft','1.0.0',2,5,2,20,4,'slow-controlled',false),
('wrist-hand-thumb-opposition','draft','1.0.0',2,5,1,20,5,'controlled',false),
('wrist-hand-soft-grip-isometric','draft','1.0.0',3,8,5,30,3,'isometric',false),
('wrist-hand-wrist-extension-isometric','draft','1.0.0',3,8,5,30,3,'isometric',false)
on conflict (stable_key) do update set
  status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,
  default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,
  default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,
  default_tempo=excluded.default_tempo;

insert into public.exercise_translations (
  exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications
)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('wrist-hand-active-mobility','fr','Mobilité active poignet-main','Mobilité douce du poignet, des doigts et de la main','Assis, avant-bras soutenu, main détendue et libre de bouger.','Bougez lentement le poignet en flexion-extension puis ouvrez et fermez doucement la main dans une amplitude confortable.','Entretenir la mobilité du poignet et de la main sans charge importante.','Gardez les mouvements petits, lents et confortables.','Forcer l’amplitude, aller vite ou serrer fortement les doigts.','Restez dans une amplitude confortable, surtout en cas d’irritation récente.','Arrêtez en cas de douleur vive, augmentation nette des fourmillements ou engourdissements, gonflement important ou autre réaction inhabituelle.','À adapter ou éviter si une immobilisation, une restriction postopératoire ou une limitation médicale du mouvement a été prescrite.'),
('wrist-hand-active-mobility','en','Active wrist-hand mobility','Gentle wrist, finger and hand mobility','Sit with the forearm supported and the hand relaxed and free to move.','Slowly move the wrist through flexion and extension, then gently open and close the hand within a comfortable range.','Maintain wrist and hand mobility without high loading.','Keep the movements small, slow, and comfortable.','Forcing range, moving too quickly, or gripping strongly.','Stay within a comfortable range, especially after recent irritation.','Stop for sharp pain, a clear increase in tingling or numbness, marked swelling, or another unusual reaction.','Modify or avoid if immobilisation, post-operative restrictions, or medical movement limits have been prescribed.'),
('wrist-hand-active-mobility','de','Aktive Handgelenk-Hand-Mobilität','Sanfte Beweglichkeit von Handgelenk, Fingern und Hand','Sitzen Sie mit unterstütztem Unterarm und entspannter, frei beweglicher Hand.','Bewegen Sie das Handgelenk langsam in Beugung und Streckung und öffnen und schließen Sie anschließend die Hand sanft in einem angenehmen Bereich.','Beweglichkeit von Handgelenk und Hand ohne hohe Belastung erhalten.','Bewegungen klein, langsam und angenehm halten.','Bewegungsweite erzwingen, zu schnell bewegen oder stark zugreifen.','Bleiben Sie besonders bei frischer Reizung in einem angenehmen Bereich.','Bei stechendem Schmerz, deutlich zunehmendem Kribbeln oder Taubheitsgefühl, starker Schwellung oder anderer ungewöhnlicher Reaktion abbrechen.','Bei Immobilisation, postoperativen Einschränkungen oder medizinisch begrenzter Bewegung anpassen oder vermeiden.'),

('wrist-hand-tendon-glide','fr','Glissement doux des tendons des doigts','Mobilité des doigts et glissement tendineux','Assis, avant-bras soutenu, poignet en position confortable et doigts détendus.','Passez lentement d’une main ouverte à une flexion légère des doigts, puis revenez. Utilisez uniquement les positions qui restent confortables.','Entretenir le mouvement des doigts et la coordination de la main.','Le mouvement doit rester souple, sans serrer fort.','Forcer les doigts en fin d’amplitude, serrer fortement ou maintenir une position douloureuse.','Réalisez la séquence lentement et sans provoquer d’augmentation des symptômes neurologiques.','Arrêtez en cas de douleur vive, augmentation durable des fourmillements ou engourdissements, blocage d’un doigt ou gonflement nettement accru.','À adapter ou éviter après chirurgie récente, immobilisation ou si certaines positions des doigts sont médicalement restreintes.'),
('wrist-hand-tendon-glide','en','Gentle finger tendon glide','Finger mobility and tendon excursion','Sit with the forearm supported, wrist comfortable, and fingers relaxed.','Move slowly from an open hand to a light finger bend, then return. Use only positions that remain comfortable.','Maintain finger movement and hand coordination.','Keep the movement smooth without gripping hard.','Forcing end range, squeezing strongly, or holding a painful position.','Perform the sequence slowly and do not provoke an increase in neurological symptoms.','Stop for sharp pain, a persistent increase in tingling or numbness, finger locking, or a marked increase in swelling.','Modify or avoid after recent surgery, immobilisation, or when certain finger positions are medically restricted.'),
('wrist-hand-tendon-glide','de','Sanftes Sehnengleiten der Finger','Fingerbeweglichkeit und Sehnengleiten','Sitzen Sie mit unterstütztem Unterarm, angenehm positioniertem Handgelenk und entspannten Fingern.','Wechseln Sie langsam von einer offenen Hand zu einer leichten Fingerbeugung und zurück. Verwenden Sie nur angenehme Positionen.','Fingerbewegung und Handkoordination erhalten.','Die Bewegung soll weich bleiben, ohne fest zu greifen.','Endstellung erzwingen, stark drücken oder eine schmerzhafte Position halten.','Langsam durchführen und keine Zunahme neurologischer Symptome provozieren.','Bei stechendem Schmerz, anhaltend zunehmendem Kribbeln oder Taubheitsgefühl, Fingerblockierung oder deutlich zunehmender Schwellung abbrechen.','Nach frischer Operation, Immobilisation oder bei medizinisch eingeschränkten Fingerpositionen anpassen oder vermeiden.'),

('wrist-hand-thumb-opposition','fr','Opposition du pouce','Mobilité et coordination du pouce','Assis, main détendue, poignet dans une position confortable.','Touchez doucement le bout du pouce avec chaque doigt l’un après l’autre, sans forcer.','Entretenir la mobilité fine et la coordination pouce-doigts.','Cherchez la précision plutôt que la force.','Appuyer fortement, accélérer ou forcer une position douloureuse du pouce.','Le mouvement doit rester léger et confortable.','Arrêtez en cas de douleur vive, blocage, augmentation nette du gonflement ou autre réaction inhabituelle.','À adapter ou éviter si le pouce est récemment opéré, immobilisé ou soumis à une restriction médicale.'),
('wrist-hand-thumb-opposition','en','Thumb opposition','Thumb mobility and coordination','Sit with the hand relaxed and the wrist in a comfortable position.','Gently touch the thumb tip to each fingertip in turn without forcing.','Maintain fine thumb-finger mobility and coordination.','Aim for precision rather than force.','Pressing hard, rushing, or forcing a painful thumb position.','Keep the movement light and comfortable.','Stop for sharp pain, locking, a clear increase in swelling, or another unusual reaction.','Modify or avoid if the thumb is recently operated on, immobilised, or medically restricted.'),
('wrist-hand-thumb-opposition','de','Daumenopposition','Daumenbeweglichkeit und Koordination','Sitzen Sie mit entspannter Hand und angenehm positioniertem Handgelenk.','Berühren Sie mit der Daumenspitze nacheinander sanft jede Fingerspitze, ohne zu erzwingen.','Feine Beweglichkeit und Koordination zwischen Daumen und Fingern erhalten.','Genauigkeit ist wichtiger als Kraft.','Stark drücken, zu schnell bewegen oder eine schmerzhafte Daumenposition erzwingen.','Die Bewegung soll leicht und angenehm bleiben.','Bei stechendem Schmerz, Blockieren, deutlich zunehmender Schwellung oder anderer ungewöhnlicher Reaktion abbrechen.','Bei frisch operiertem, immobilisiertem oder medizinisch eingeschränktem Daumen anpassen oder vermeiden.'),

('wrist-hand-soft-grip-isometric','fr','Préhension douce isométrique','Force de préhension légère et contrôle de la main','Assis, avant-bras soutenu, tenez une serviette roulée ou un objet souple dans la main.','Serrez doucement l’objet sans aller à la force maximale, maintenez quelques secondes puis relâchez complètement.','Développer progressivement la tolérance à la préhension et la force fonctionnelle de la main.','Utilisez une pression légère à modérée, jamais maximale.','Serrer trop fort, retenir la respiration ou continuer malgré une augmentation des symptômes.','Choisissez un objet souple et une intensité confortable.','Arrêtez en cas de douleur vive, augmentation des fourmillements ou engourdissements, crampe persistante ou gonflement accru.','Peut être inadapté en phase inflammatoire aiguë, après chirurgie récente ou si la préhension résistée est temporairement interdite.'),
('wrist-hand-soft-grip-isometric','en','Gentle isometric grip','Light grip strength and hand control','Sit with the forearm supported and hold a rolled towel or another soft object.','Gently squeeze the object without using maximal force, hold for a few seconds, then fully relax.','Gradually build tolerance to gripping and functional hand strength.','Use light-to-moderate pressure, never maximal force.','Squeezing too hard, holding the breath, or continuing despite increasing symptoms.','Choose a soft object and a comfortable effort level.','Stop for sharp pain, increased tingling or numbness, persistent cramping, or increased swelling.','May be unsuitable during acute inflammation, after recent surgery, or when resisted gripping is temporarily restricted.'),
('wrist-hand-soft-grip-isometric','de','Sanfter isometrischer Griff','Leichte Griffkraft und Handkontrolle','Sitzen Sie mit unterstütztem Unterarm und halten Sie ein gerolltes Handtuch oder einen weichen Gegenstand.','Drücken Sie den Gegenstand sanft ohne Maximalkraft, halten Sie einige Sekunden und lösen Sie vollständig.','Griffbelastbarkeit und funktionelle Handkraft schrittweise aufbauen.','Leichten bis mäßigen Druck verwenden, niemals Maximalkraft.','Zu stark drücken, Luft anhalten oder trotz zunehmender Beschwerden weitermachen.','Weichen Gegenstand und angenehme Intensität wählen.','Bei stechendem Schmerz, zunehmendem Kribbeln oder Taubheitsgefühl, anhaltendem Krampf oder zunehmender Schwellung abbrechen.','Kann bei akuter Entzündung, nach frischer Operation oder bei vorübergehend verbotenem Widerstandsgriff ungeeignet sein.'),

('wrist-hand-wrist-extension-isometric','fr','Extension isométrique du poignet','Contrôle des extenseurs du poignet','Assis, avant-bras soutenu, poignet en position neutre ou confortable.','Placez l’autre main sur le dos de la main à travailler. Poussez très doucement comme pour relever le poignet sans laisser de mouvement visible. Maintenez puis relâchez.','Renforcer progressivement le contrôle du poignet avec peu de mouvement articulaire.','Commencez avec une faible résistance.','Forcer fortement, laisser le poignet bouger ou provoquer des symptômes dans les doigts.','La contraction doit rester légère et confortable.','Arrêtez en cas de douleur vive, augmentation nette des fourmillements ou engourdissements, faiblesse inhabituelle ou gonflement accru.','À adapter ou éviter après chirurgie récente, en phase inflammatoire aiguë ou si la contraction résistée du poignet est limitée médicalement.'),
('wrist-hand-wrist-extension-isometric','en','Isometric wrist extension','Wrist extensor control','Sit with the forearm supported and the wrist in a neutral or comfortable position.','Place the other hand on the back of the working hand. Gently push as if lifting the wrist without allowing visible movement. Hold, then relax.','Gradually strengthen wrist control with little joint movement.','Start with very light resistance.','Pushing hard, allowing wrist movement, or provoking symptoms into the fingers.','Keep the contraction light and comfortable.','Stop for sharp pain, a clear increase in tingling or numbness, unusual weakness, or increased swelling.','Modify or avoid after recent surgery, during acute inflammation, or when resisted wrist contraction is medically restricted.'),
('wrist-hand-wrist-extension-isometric','de','Isometrische Handgelenkstreckung','Kontrolle der Handgelenkstrecker','Sitzen Sie mit unterstütztem Unterarm und neutral oder angenehm positioniertem Handgelenk.','Legen Sie die andere Hand auf den Handrücken. Drücken Sie sanft, als wollten Sie das Handgelenk anheben, ohne sichtbare Bewegung. Halten, dann lösen.','Handgelenkskontrolle mit wenig Gelenkbewegung schrittweise kräftigen.','Mit sehr geringem Widerstand beginnen.','Zu stark drücken, Bewegung zulassen oder Symptome in den Fingern provozieren.','Die Anspannung soll leicht und angenehm bleiben.','Bei stechendem Schmerz, deutlich zunehmendem Kribbeln oder Taubheitsgefühl, ungewöhnlicher Schwäche oder zunehmender Schwellung abbrechen.','Nach frischer Operation, bei akuter Entzündung oder medizinisch eingeschränkter Widerstandsbelastung des Handgelenks anpassen oder vermeiden.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set
  name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,
  why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,
  safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'wrist-hand',true from public.exercises
where stable_key in ('wrist-hand-active-mobility','wrist-hand-tendon-glide','wrist-hand-thumb-opposition','wrist-hand-soft-grip-isometric','wrist-hand-wrist-extension-isometric')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('wrist-hand-soft-grip-isometric','very-soft-grip','easy',0,3,6,3,30,'isometric'),
('wrist-hand-soft-grip-isometric','soft-grip-standard','standard',1,3,8,5,30,'isometric'),
('wrist-hand-soft-grip-isometric','longer-hold-grip','hard',2,3,8,8,45,'isometric'),
('wrist-hand-wrist-extension-isometric','very-light-resistance','easy',0,3,6,3,30,'isometric'),
('wrist-hand-wrist-extension-isometric','light-resistance-standard','standard',1,3,8,5,30,'isometric'),
('wrist-hand-wrist-extension-isometric','longer-hold-resistance','hard',2,3,8,8,45,'isometric')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set
  difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,
  sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,
  hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,
  tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('wrist-hand-soft-grip-isometric','very-soft-grip','fr','Préhension très douce','Serrez à peine un objet très souple pendant quelques secondes.','Choisissez cette variante si la main est sensible ou peu tolérante à la charge.'),
('wrist-hand-soft-grip-isometric','very-soft-grip','en','Very gentle grip','Barely squeeze a very soft object for a few seconds.','Use this option when the hand is sensitive or poorly tolerant of load.'),
('wrist-hand-soft-grip-isometric','very-soft-grip','de','Sehr sanfter Griff','Einen sehr weichen Gegenstand nur leicht für einige Sekunden drücken.','Diese Variante bei empfindlicher Hand oder geringer Belastungstoleranz wählen.'),
('wrist-hand-soft-grip-isometric','soft-grip-standard','fr','Préhension douce standard','Serrez doucement une serviette roulée ou un objet souple puis relâchez complètement.','Gardez l’effort sous-maximal.'),
('wrist-hand-soft-grip-isometric','soft-grip-standard','en','Standard gentle grip','Gently squeeze a rolled towel or soft object, then fully relax.','Keep the effort submaximal.'),
('wrist-hand-soft-grip-isometric','soft-grip-standard','de','Standard sanfter Griff','Ein gerolltes Handtuch oder einen weichen Gegenstand sanft drücken und vollständig lösen.','Belastung unterhalb der Maximalkraft halten.'),
('wrist-hand-soft-grip-isometric','longer-hold-grip','fr','Préhension douce avec maintien prolongé','Gardez la même intensité légère mais maintenez un peu plus longtemps.','Augmentez la durée avant d’augmenter la force.'),
('wrist-hand-soft-grip-isometric','longer-hold-grip','en','Gentle grip with longer hold','Keep the same light effort but hold a little longer.','Increase duration before increasing force.'),
('wrist-hand-soft-grip-isometric','longer-hold-grip','de','Sanfter Griff mit längerem Halten','Gleiche leichte Intensität etwas länger halten.','Zuerst Dauer, dann Kraft steigern.'),
('wrist-hand-wrist-extension-isometric','very-light-resistance','fr','Extension du poignet avec résistance très légère','Utilisez seulement une pression minimale de l’autre main.','Commencez très doucement et restez sans symptôme accru.'),
('wrist-hand-wrist-extension-isometric','very-light-resistance','en','Wrist extension with very light resistance','Use only minimal pressure from the other hand.','Start very gently and avoid increasing symptoms.'),
('wrist-hand-wrist-extension-isometric','very-light-resistance','de','Handgelenkstreckung mit sehr leichtem Widerstand','Nur minimalen Druck mit der anderen Hand verwenden.','Sehr sanft beginnen und keine Beschwerdezunahme provozieren.'),
('wrist-hand-wrist-extension-isometric','light-resistance-standard','fr','Extension isométrique standard','Appliquez une légère résistance tout en gardant le poignet immobile.','Le poignet reste stable pendant toute la contraction.'),
('wrist-hand-wrist-extension-isometric','light-resistance-standard','en','Standard isometric wrist extension','Apply light resistance while keeping the wrist still.','Keep the wrist steady throughout the contraction.'),
('wrist-hand-wrist-extension-isometric','light-resistance-standard','de','Standard isometrische Handgelenkstreckung','Leichten Widerstand geben und das Handgelenk unbewegt halten.','Handgelenk während der gesamten Anspannung stabil halten.'),
('wrist-hand-wrist-extension-isometric','longer-hold-resistance','fr','Extension isométrique avec maintien prolongé','Gardez une faible résistance mais maintenez la contraction un peu plus longtemps.','Augmentez la durée sans augmenter brutalement la force.'),
('wrist-hand-wrist-extension-isometric','longer-hold-resistance','en','Isometric wrist extension with longer hold','Keep the resistance light but hold the contraction a little longer.','Increase duration without abruptly increasing force.'),
('wrist-hand-wrist-extension-isometric','longer-hold-resistance','de','Isometrische Handgelenkstreckung mit längerem Halten','Widerstand leicht halten und die Anspannung etwas länger halten.','Dauer erhöhen, ohne die Kraft plötzlich zu steigern.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;