insert into public.exercises (
  stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable
) values
('ankle-foot-active-mobility','draft','1.0.0',2,12,0,20,5,'slow-controlled',false),
('ankle-foot-supported-calf-raise','draft','1.0.0',3,10,0,45,3,'controlled',false),
('ankle-foot-knee-to-wall-mobility','draft','1.0.0',2,10,0,30,4,'slow-controlled',false),
('ankle-foot-supported-balance','draft','1.0.0',3,3,20,30,4,'steady',false),
('ankle-foot-short-foot-activation','draft','1.0.0',3,8,5,30,4,'isometric',false)
on conflict (stable_key) do update set
  status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,
  default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,
  default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,
  default_tempo=excluded.default_tempo;

insert into public.exercise_translations (
  exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications
)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('ankle-foot-active-mobility','fr','Mobilité active cheville-pied','Mobilité douce de la cheville et contrôle du pied','Assis ou allongé, jambe soutenue et pied libre de bouger.','Alternez lentement flexion et extension de cheville dans une amplitude confortable, sans forcer.','Entretenir la mobilité et préparer le pied aux exercices suivants.','Gardez le mouvement lent et fluide.','Aller trop vite, forcer une amplitude douloureuse ou crisper les orteils.','Restez dans une amplitude confortable, surtout après une blessure récente.','Arrêtez en cas de douleur vive, gonflement nettement accru, blocage ou autre réaction inhabituelle.','À adapter ou éviter si une restriction de mouvement ou de mise en charge a été prescrite.'),
('ankle-foot-active-mobility','en','Active ankle-foot mobility','Gentle ankle mobility and foot control','Sit or lie with the leg supported and the foot free to move.','Slowly alternate ankle flexion and extension within a comfortable range without forcing.','Maintain mobility and prepare the foot for the exercises that follow.','Keep the movement slow and smooth.','Moving too quickly, forcing painful range, or gripping with the toes.','Stay within a comfortable range, especially after a recent injury.','Stop for sharp pain, a marked increase in swelling, locking, or another unusual reaction.','Modify or avoid if a movement or weight-bearing restriction has been prescribed.'),
('ankle-foot-active-mobility','de','Aktive Sprunggelenk-Fuß-Mobilität','Sanfte Sprunggelenksmobilität und Fußkontrolle','Sitzen oder liegen Sie mit unterstütztem Bein und frei beweglichem Fuß.','Bewegen Sie das Sprunggelenk langsam in Beugung und Streckung innerhalb eines angenehmen Bereichs.','Beweglichkeit erhalten und den Fuß auf weitere Übungen vorbereiten.','Langsam und flüssig bewegen.','Zu schnell bewegen, schmerzhafte Bewegungsweite erzwingen oder die Zehen verkrampfen.','Bleiben Sie besonders nach einer frischen Verletzung in einem angenehmen Bewegungsbereich.','Bei stechendem Schmerz, deutlich zunehmender Schwellung, Blockieren oder anderer ungewöhnlicher Reaktion abbrechen.','Bei verordneter Bewegungs- oder Belastungseinschränkung anpassen oder vermeiden.'),
('ankle-foot-supported-calf-raise','fr','Élévation des talons avec appui','Mollet, cheville et contrôle de la poussée','Debout face à un support stable, pieds parallèles et poids réparti confortablement.','Montez progressivement sur l’avant-pied, marquez un court contrôle puis redescendez lentement.','Renforcer progressivement le mollet et la capacité de propulsion.','Montez et redescendez avec contrôle, sans rebond.','Rouler les chevilles vers l’intérieur ou l’extérieur, prendre de l’élan ou monter dans la douleur.','Utilisez un support stable et une amplitude confortable.','Arrêtez en cas de douleur vive, perte d’équilibre, sensation de rupture, gonflement nettement accru ou autre symptôme inquiétant.','Peut être inadapté en phase aiguë ou si la mise en charge n’est pas autorisée.'),
('ankle-foot-supported-calf-raise','en','Supported calf raise','Calf strength, ankle control and push-off','Stand facing a stable support with feet parallel and weight comfortably distributed.','Rise gradually onto the forefoot, pause briefly with control, then lower slowly.','Progressively strengthen the calf and push-off capacity.','Rise and lower with control without bouncing.','Letting the ankles roll in or out, using momentum, or pushing into pain.','Use a stable support and a comfortable range.','Stop for sharp pain, loss of balance, a tearing sensation, a marked increase in swelling, or another concerning symptom.','May be unsuitable in an acute phase or when weight bearing is not allowed.'),
('ankle-foot-supported-calf-raise','de','Fersenheben mit Unterstützung','Wadenkraft, Sprunggelenkskontrolle und Abstoß','Stehen Sie vor einer stabilen Stütze, Füße parallel und Gewicht angenehm verteilt.','Heben Sie die Fersen kontrolliert an, halten Sie kurz und senken Sie langsam wieder ab.','Wadenkraft und Abstoßfähigkeit schrittweise verbessern.','Kontrolliert heben und senken, ohne zu federn.','Sprunggelenke nach innen oder außen kippen lassen, Schwung nutzen oder in Schmerz hineinarbeiten.','Eine stabile Stütze und einen angenehmen Bewegungsumfang verwenden.','Bei stechendem Schmerz, Gleichgewichtsverlust, Reißgefühl, deutlich zunehmender Schwellung oder anderen bedenklichen Symptomen abbrechen.','Kann in einer akuten Phase oder bei nicht erlaubter Belastung ungeeignet sein.'),
('ankle-foot-knee-to-wall-mobility','fr','Mobilité cheville genou-vers-mur','Dorsiflexion contrôlée de cheville','Debout face à un mur, un pied devant, talon au sol et support disponible.','Avancez doucement le genou vers le mur en gardant le talon au sol, puis revenez.','Travailler progressivement la mobilité de cheville utile à la marche et aux escaliers.','Gardez le talon au sol et le genou dans l’axe du pied.','Décoller le talon, forcer la douleur ou laisser le genou s’effondrer vers l’intérieur.','Utilisez une petite amplitude et un support stable si nécessaire.','Arrêtez en cas de douleur vive, pincement marqué, instabilité ou gonflement nettement accru.','À éviter ou adapter si la dorsiflexion est médicalement limitée ou si l’appui est interdit.'),
('ankle-foot-knee-to-wall-mobility','en','Knee-to-wall ankle mobility','Controlled ankle dorsiflexion','Stand facing a wall with one foot forward, heel down, and support available.','Gently move the knee toward the wall while keeping the heel down, then return.','Gradually work on ankle mobility used in walking and stairs.','Keep the heel down and the knee aligned with the foot.','Lifting the heel, forcing pain, or letting the knee collapse inward.','Use a small range and stable support if needed.','Stop for sharp pain, marked pinching, instability, or a clear increase in swelling.','Avoid or modify if dorsiflexion is medically restricted or weight bearing is not allowed.'),
('ankle-foot-knee-to-wall-mobility','de','Sprunggelenksmobilität Knie-zur-Wand','Kontrollierte Dorsalflexion des Sprunggelenks','Stehen Sie vor einer Wand, ein Fuß vorne, Ferse am Boden und Stütze verfügbar.','Bewegen Sie das Knie sanft zur Wand, ohne die Ferse anzuheben, und gehen Sie wieder zurück.','Sprunggelenksbeweglichkeit für Gehen und Treppen schrittweise verbessern.','Ferse am Boden lassen und das Knie in Fußrichtung führen.','Ferse anheben, Schmerzen erzwingen oder Knie nach innen kippen lassen.','Kleine Bewegungsweite wählen und bei Bedarf eine stabile Stütze nutzen.','Bei stechendem Schmerz, deutlichem Einklemmgefühl, Instabilität oder klar zunehmender Schwellung abbrechen.','Bei medizinisch eingeschränkter Dorsalflexion oder Belastungsverbot vermeiden oder anpassen.'),
('ankle-foot-supported-balance','fr','Équilibre avec appui','Stabilité de cheville et contrôle postural','Debout près d’un support stable, pieds dans une position sûre.','Réduisez progressivement la largeur d’appui ou déchargez légèrement un pied tout en gardant un contact de sécurité.','Améliorer le contrôle de la cheville et la stabilité en position debout.','La sécurité passe avant la difficulté.','Retirer l’appui trop tôt, fermer les yeux ou choisir une position instable.','Restez près d’un support stable et pratiquez sur un sol dégagé.','Arrêtez en cas de vertige, perte d’équilibre répétée, douleur vive ou sensation d’instabilité importante.','À réaliser avec assistance si l’équilibre debout n’est pas sûr de façon autonome.'),
('ankle-foot-supported-balance','en','Supported balance','Ankle stability and postural control','Stand near a stable support with the feet in a safe position.','Gradually narrow the base of support or lightly unload one foot while keeping safety contact available.','Improve ankle control and standing stability.','Safety comes before difficulty.','Removing support too early, closing the eyes, or choosing an unstable position.','Stay close to a stable support and practise in a clear area.','Stop for dizziness, repeated loss of balance, sharp pain, or marked instability.','Use assistance if standing balance is not independently safe.'),
('ankle-foot-supported-balance','de','Gleichgewicht mit Unterstützung','Sprunggelenksstabilität und Haltungskontrolle','Stehen Sie nahe einer stabilen Stütze in einer sicheren Fußposition.','Verkleinern Sie schrittweise die Standfläche oder entlasten Sie einen Fuß leicht, während eine Sicherheitsstütze verfügbar bleibt.','Sprunggelenkskontrolle und Standstabilität verbessern.','Sicherheit geht vor Schwierigkeit.','Unterstützung zu früh wegnehmen, Augen schließen oder eine unsichere Position wählen.','Bleiben Sie nahe einer stabilen Stütze und üben Sie auf freier Fläche.','Bei Schwindel, wiederholtem Gleichgewichtsverlust, stechendem Schmerz oder deutlicher Instabilität abbrechen.','Mit Unterstützung durchführen, wenn freies Stehen nicht sicher möglich ist.'),
('ankle-foot-short-foot-activation','fr','Activation de la voûte plantaire','Muscles intrinsèques du pied et contrôle de la voûte','Assis, pied posé à plat, orteils détendus.','Raccourcissez très légèrement le pied en rapprochant l’avant-pied du talon sans crisper ni recourber fortement les orteils. Maintenez puis relâchez.','Améliorer le contrôle actif de la voûte plantaire sans charge élevée.','Pensez à créer une légère tension sous la voûte sans agripper le sol avec les orteils.','Crisper les orteils, rouler le pied vers l’extérieur ou appuyer trop fort.','Commencez assis et sans douleur; la contraction doit rester douce.','Arrêtez en cas de douleur vive, crampe persistante, engourdissement accru ou réaction inhabituelle.','À adapter si l’avant-pied ou les orteils sont très sensibles ou récemment opérés.'),
('ankle-foot-short-foot-activation','en','Short-foot activation','Intrinsic foot muscles and arch control','Sit with the foot flat and the toes relaxed.','Very gently shorten the foot by drawing the forefoot toward the heel without gripping or strongly curling the toes. Hold, then relax.','Improve active arch control without high loading.','Create gentle tension under the arch without clawing the floor with the toes.','Curling the toes, rolling the foot outward, or pressing too hard.','Start seated and pain-free; the contraction should stay gentle.','Stop for sharp pain, persistent cramping, increased numbness, or another unusual reaction.','Modify if the forefoot or toes are very sensitive or recently operated on.'),
('ankle-foot-short-foot-activation','de','Aktivierung des Fußgewölbes','Intrinsische Fußmuskeln und Gewölbekontrolle','Sitzen Sie mit flach aufgestelltem Fuß und entspannten Zehen.','Verkürzen Sie den Fuß sehr leicht, indem Sie den Vorfuß zur Ferse ziehen, ohne die Zehen fest einzukrallen. Halten, dann lösen.','Aktive Gewölbekontrolle ohne hohe Belastung verbessern.','Leichte Spannung im Fußgewölbe erzeugen, ohne den Boden mit den Zehen zu greifen.','Zehen einkrallen, Fuß nach außen rollen oder zu stark drücken.','Im Sitzen und schmerzfrei beginnen; die Spannung soll sanft bleiben.','Bei stechendem Schmerz, anhaltendem Krampf, zunehmender Taubheit oder anderer ungewöhnlicher Reaktion abbrechen.','Bei stark empfindlichem oder frisch operiertem Vorfuß/Zehenbereich anpassen.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set
  name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,
  why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,
  safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'ankle-foot',true from public.exercises
where stable_key in ('ankle-foot-active-mobility','ankle-foot-supported-calf-raise','ankle-foot-knee-to-wall-mobility','ankle-foot-supported-balance','ankle-foot-short-foot-activation')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('ankle-foot-supported-calf-raise','seated-calf-raise','easy',0,3,10,null,45,'controlled'),
('ankle-foot-supported-calf-raise','bilateral-standing','standard',1,3,10,null,45,'controlled'),
('ankle-foot-supported-calf-raise','reduced-support-standing','hard',2,3,10,null,60,'slow-controlled'),
('ankle-foot-supported-balance','narrow-stance-supported','easy',0,3,3,15,30,'steady'),
('ankle-foot-supported-balance','single-leg-light-support','standard',1,3,3,20,30,'steady'),
('ankle-foot-supported-balance','single-leg-reduced-support','hard',2,3,3,20,45,'steady')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,
sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,
rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('ankle-foot-supported-calf-raise','seated-calf-raise','fr','Élévation des talons assis','Assis, montez doucement les talons puis redescendez avec contrôle.','Utilisez cette variante si la mise en charge debout est trop exigeante.'),
('ankle-foot-supported-calf-raise','seated-calf-raise','en','Seated calf raise','While seated, gently lift the heels and lower with control.','Use this option when standing loading is too demanding.'),
('ankle-foot-supported-calf-raise','seated-calf-raise','de','Fersenheben im Sitzen','Heben Sie im Sitzen die Fersen sanft an und senken Sie kontrolliert ab.','Diese Variante nutzen, wenn die Belastung im Stand zu anspruchsvoll ist.'),
('ankle-foot-supported-calf-raise','bilateral-standing','fr','Élévation bilatérale des talons','Debout avec appui, montez sur les deux avant-pieds puis redescendez lentement.','Répartissez la charge de façon confortable entre les deux pieds.'),
('ankle-foot-supported-calf-raise','bilateral-standing','en','Bilateral standing calf raise','With support, rise onto both forefeet and lower slowly.','Distribute the load comfortably between both feet.'),
('ankle-foot-supported-calf-raise','bilateral-standing','de','Beidbeiniges Fersenheben im Stand','Mit Unterstützung auf beide Vorfüße steigen und langsam absenken.','Belastung angenehm auf beide Füße verteilen.'),
('ankle-foot-supported-calf-raise','reduced-support-standing','fr','Élévation des talons avec appui réduit','Effectuez la version debout avec moins d’aide des mains seulement si elle reste stable et confortable.','Réduisez l’appui avant d’augmenter les répétitions.'),
('ankle-foot-supported-calf-raise','reduced-support-standing','en','Standing calf raise with reduced support','Perform the standing version with less hand support only when it remains stable and comfortable.','Reduce support before increasing repetitions.'),
('ankle-foot-supported-calf-raise','reduced-support-standing','de','Fersenheben im Stand mit weniger Unterstützung','Die Standvariante nur mit weniger Handstütze durchführen, wenn sie stabil und angenehm bleibt.','Zuerst Unterstützung reduzieren, dann Wiederholungen steigern.'),
('ankle-foot-supported-balance','narrow-stance-supported','fr','Équilibre pieds rapprochés avec appui','Rapprochez les pieds tout en gardant les mains près d’un support stable.','Choisissez une position qui reste sûre.'),
('ankle-foot-supported-balance','narrow-stance-supported','en','Supported narrow-stance balance','Bring the feet closer while keeping the hands near a stable support.','Choose a position that remains safe.'),
('ankle-foot-supported-balance','narrow-stance-supported','de','Enger Stand mit Unterstützung','Füße näher zusammenstellen und die Hände nahe an einer stabilen Stütze halten.','Eine Position wählen, die sicher bleibt.'),
('ankle-foot-supported-balance','single-leg-light-support','fr','Équilibre unipodal avec appui léger','Déchargez un pied et gardez un contact léger avec le support.','Ne retirez pas totalement l’appui si la stabilité n’est pas fiable.'),
('ankle-foot-supported-balance','single-leg-light-support','en','Single-leg balance with light support','Unload one foot while keeping light contact with the support.','Do not remove support completely if stability is unreliable.'),
('ankle-foot-supported-balance','single-leg-light-support','de','Einbeinstand mit leichter Unterstützung','Einen Fuß entlasten und leichten Kontakt zur Stütze behalten.','Unterstützung nicht vollständig lösen, wenn die Stabilität unsicher ist.'),
('ankle-foot-supported-balance','single-leg-reduced-support','fr','Équilibre unipodal avec appui réduit','Réduisez progressivement le contact avec le support sans compromettre la sécurité.','La progression vient de la diminution de l’aide, pas de la prise de risque.'),
('ankle-foot-supported-balance','single-leg-reduced-support','en','Single-leg balance with reduced support','Gradually reduce contact with the support without compromising safety.','Progress by reducing assistance, not by taking risks.'),
('ankle-foot-supported-balance','single-leg-reduced-support','de','Einbeinstand mit reduzierter Unterstützung','Kontakt zur Stütze schrittweise reduzieren, ohne die Sicherheit zu gefährden.','Fortschritt entsteht durch weniger Hilfe, nicht durch mehr Risiko.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;