insert into public.programme_phases (programme_id,stable_key,sort_order,status) values (10,'foundation-control',0,'draft'),(10,'strength-balance',1,'draft') on conflict (programme_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status;
insert into public.programme_phase_translations (phase_id,language,name,objective)
select pp.id,v.language,v.name,v.objective from public.programme_phases pp join (values
('foundation-control','fr','Phase 1 — Contrôle et fondations','Réintroduire respiration, tronc, transferts et marche légère avec sécurité.'),('foundation-control','en','Phase 1 — Control and foundations','Reintroduce breathing, trunk control, transfers, and light marching safely.'),('foundation-control','de','Phase 1 — Kontrolle und Grundlagen','Atmung, Rumpfkontrolle, Transfers und leichtes Marschieren sicher wieder einführen.'),
('strength-balance','fr','Phase 2 — Force et équilibre','Développer force fonctionnelle, équilibre et autonomie avec progression graduelle.'),('strength-balance','en','Phase 2 — Strength and balance','Build functional strength, balance, and independence gradually.'),('strength-balance','de','Phase 2 — Kraft und Gleichgewicht','Funktionelle Kraft, Gleichgewicht und Selbstständigkeit schrittweise aufbauen.')) v(phase_key,language,name,objective) on pp.programme_id=10 and pp.stable_key=v.phase_key on conflict (phase_id,language) do update set name=excluded.name,objective=excluded.objective;
insert into public.programme_sessions (phase_id,stable_key,sort_order,status,estimated_duration_minutes)
select pp.id,v.stable_key,v.sort_order,'draft',v.minutes from public.programme_phases pp join (values ('foundation-control','session-foundation-a',0,12),('foundation-control','session-control-b',1,14),('strength-balance','session-strength-a',0,15),('strength-balance','session-balance-b',1,16)) v(phase_key,stable_key,sort_order,minutes) on pp.programme_id=10 and pp.stable_key=v.phase_key on conflict (phase_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status,estimated_duration_minutes=excluded.estimated_duration_minutes;
insert into public.programme_session_translations (session_id,language,name,intro,completion_message)
select ps.id,v.language,v.name,v.intro,v.done from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-foundation-a','fr','Séance 1 — Respiration et transfert','Commencez par le contrôle du tronc et un transfert simple.','Terminé : gardez un effort confortable.'),('session-foundation-a','en','Session 1 — Breathing and transfer','Start with trunk control and a simple transfer.','Complete: keep effort comfortable.'),('session-foundation-a','de','Einheit 1 — Atmung und Transfer','Mit Rumpfkontrolle und einfachem Transfer beginnen.','Fertig: Belastung angenehm halten.'),
('session-control-b','fr','Séance 2 — Marche et coordination','Ajoutez marche sur place et coordination pelvienne douce selon pertinence.','Terminé : la qualité prime sur la quantité.'),('session-control-b','en','Session 2 — Marching and coordination','Add supported marching and gentle pelvic coordination when relevant.','Complete: quality matters more than quantity.'),('session-control-b','de','Einheit 2 — Marschieren und Koordination','Unterstütztes Marschieren und bei Bedarf sanfte Beckenkoordination ergänzen.','Fertig: Qualität vor Menge.'),
('session-strength-a','fr','Séance 3 — Force fonctionnelle','Progressez l’assis-debout et la marche sur place.','Terminé : augmentez progressivement.'),('session-strength-a','en','Session 3 — Functional strength','Progress sit-to-stand and marching.','Complete: increase gradually.'),('session-strength-a','de','Einheit 3 — Funktionelle Kraft','Aufstehen/Hinsetzen und Marschieren steigern.','Fertig: schrittweise steigern.'),
('session-balance-b','fr','Séance 4 — Équilibre et autonomie','Combinez transfert, équilibre sécurisé et marche légère.','Terminé : conservez toujours une marge de sécurité.'),('session-balance-b','en','Session 4 — Balance and independence','Combine transfers, supported balance, and light marching.','Complete: always keep a safety margin.'),('session-balance-b','de','Einheit 4 — Gleichgewicht und Selbstständigkeit','Transfers, gesichertes Gleichgewicht und leichtes Marschieren kombinieren.','Fertig: immer Sicherheitsreserve behalten.')) v(session_key,language,name,intro,done) on pp.programme_id=10 and ps.stable_key=v.session_key on conflict (session_id,language) do update set name=excluded.name,intro=excluded.intro,completion_message=excluded.completion_message;
insert into public.programme_session_exercises (session_id,exercise_id,exercise_variant_id,sort_order,is_optional,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select ps.id,e.id,ev.id,v.sort_order,false,v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-foundation-a','reconditioning-core-breathing-brace',null::text,0,2,6,5,20,'slow-controlled'),('session-foundation-a','reconditioning-core-sit-to-stand','high-chair-arms',1,2,6,null::integer,45,'controlled'),('session-foundation-a','reconditioning-core-supported-balance','wide-stance-supported',2,3,3,15,30,'steady'),
('session-control-b','reconditioning-core-breathing-brace',null::text,0,2,6,5,20,'slow-controlled'),('session-control-b','reconditioning-core-supported-march',null::text,1,3,8,null::integer,30,'controlled'),('session-control-b','reconditioning-core-pelvic-floor-coordination',null::text,2,2,6,3,20,'slow-controlled'),
('session-strength-a','reconditioning-core-sit-to-stand','standard-chair',0,3,8,null::integer,45,'controlled'),('session-strength-a','reconditioning-core-supported-march',null::text,1,3,10,null::integer,30,'controlled'),('session-strength-a','reconditioning-core-supported-balance','narrow-stance-supported',2,3,3,20,30,'steady'),
('session-balance-b','reconditioning-core-sit-to-stand','slow-lowering',0,3,8,null::integer,60,'3-second-lowering'),('session-balance-b','reconditioning-core-supported-balance','reduced-hand-support',1,3,3,20,45,'steady'),('session-balance-b','reconditioning-core-supported-march',null::text,2,3,10,null::integer,30,'controlled')) v(session_key,exercise_key,variant_key,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on pp.programme_id=10 and ps.stable_key=v.session_key join public.exercises e on e.stable_key=v.exercise_key left join public.exercise_variants ev on ev.exercise_id=e.id and ev.stable_key=v.variant_key
on conflict (session_id,sort_order) do update set exercise_id=excluded.exercise_id,exercise_variant_id=excluded.exercise_variant_id,is_optional=excluded.is_optional,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;