insert into public.exercises (stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable) values
('mobility-flexibility-breathing-reset','draft','1.0.0',2,6,5,20,5,'slow-controlled',false),
('mobility-flexibility-thoracic-rotation','draft','1.0.0',2,6,0,20,4,'slow-controlled',false),
('mobility-flexibility-hip-hinge','draft','1.0.0',2,8,0,30,4,'controlled',false),
('mobility-flexibility-calf-stretch','draft','1.0.0',2,3,20,20,5,'steady',false),
('mobility-flexibility-supported-flow','draft','1.0.0',2,6,0,30,4,'slow-controlled',false)
on conflict (stable_key) do update set status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,default_tempo=excluded.default_tempo;

insert into public.exercise_translations (exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications from public.exercises e join (values
('mobility-flexibility-breathing-reset','fr','Respiration et relâchement','Respiration et détente globale','Assis ou allongé confortablement.','Respirez lentement et relâchez les épaules, la mâchoire et le tronc.','Préparer la mobilité sans tension excessive.','Cherchez le relâchement.','Bloquer la respiration ou forcer une posture.','Restez confortable.','Arrêtez en cas de malaise, douleur vive ou essoufflement inhabituel.','À adapter selon les restrictions médicales.'),
('mobility-flexibility-breathing-reset','en','Breathing and relaxation','Breathing and whole-body relaxation','Sit or lie comfortably.','Breathe slowly and relax the shoulders, jaw, and trunk.','Prepare mobility without excessive tension.','Aim for relaxation.','Holding the breath or forcing posture.','Stay comfortable.','Stop for faintness, sharp pain, or unusual breathlessness.','Modify according to medical restrictions.'),
('mobility-flexibility-breathing-reset','de','Atmung und Entspannung','Atmung und Ganzkörperentspannung','Bequem sitzen oder liegen.','Langsam atmen und Schultern, Kiefer und Rumpf entspannen.','Beweglichkeit ohne unnötige Spannung vorbereiten.','Entspannung anstreben.','Luft anhalten oder Haltung erzwingen.','Komfortabel bleiben.','Bei Kreislaufproblemen, stechendem Schmerz oder ungewöhnlicher Atemnot abbrechen.','An medizinische Einschränkungen anpassen.'),
('mobility-flexibility-thoracic-rotation','fr','Rotation thoracique douce','Mobilité du haut du dos','Assis ou en décubitus latéral confortable.','Tournez doucement le haut du tronc dans une petite amplitude puis revenez.','Entretenir la mobilité thoracique.','Gardez le mouvement lent.','Forcer la rotation ou créer une douleur.','Amplitude confortable uniquement.','Arrêtez en cas de douleur vive, vertige ou irradiation nouvelle.','À adapter si la rotation est médicalement limitée.'),
('mobility-flexibility-thoracic-rotation','en','Gentle thoracic rotation','Upper-back mobility','Sit or lie comfortably on your side.','Gently rotate the upper trunk through a small range, then return.','Maintain thoracic mobility.','Keep the movement slow.','Forcing rotation or provoking pain.','Use only a comfortable range.','Stop for sharp pain, dizziness, or new radiating symptoms.','Modify if rotation is medically restricted.'),
('mobility-flexibility-thoracic-rotation','de','Sanfte Brustwirbelsäulenrotation','Beweglichkeit des oberen Rückens','Bequem sitzen oder seitlich liegen.','Oberen Rumpf sanft in kleiner Weite drehen und zurückkehren.','Brustwirbelsäulenbeweglichkeit erhalten.','Langsam bewegen.','Rotation erzwingen oder Schmerz provozieren.','Nur angenehme Bewegungsweite.','Bei stechendem Schmerz, Schwindel oder neuer Ausstrahlung abbrechen.','Bei medizinisch eingeschränkter Rotation anpassen.'),
('mobility-flexibility-hip-hinge','fr','Charnière de hanche contrôlée','Mobilité des hanches et contrôle du tronc','Debout près d’un support, pieds stables.','Reculez doucement les hanches en gardant le tronc contrôlé puis revenez.','Améliorer une mobilité fonctionnelle utile au quotidien.','Le mouvement vient des hanches.','Arrondir excessivement le dos ou aller trop loin.','Utilisez un support si nécessaire.','Arrêtez en cas de douleur vive, vertige ou perte d’équilibre.','À adapter si la flexion de hanche ou la station debout est limitée.'),
('mobility-flexibility-hip-hinge','en','Controlled hip hinge','Hip mobility and trunk control','Stand near support with stable feet.','Gently move the hips backward while keeping the trunk controlled, then return.','Improve functional mobility for daily tasks.','Move from the hips.','Excessively rounding the back or moving too far.','Use support if needed.','Stop for sharp pain, dizziness, or loss of balance.','Modify if hip flexion or standing is restricted.'),
('mobility-flexibility-hip-hinge','de','Kontrolliertes Hüftbeugen','Hüftbeweglichkeit und Rumpfkontrolle','Nahe einer Stütze stabil stehen.','Hüften sanft nach hinten führen, Rumpf kontrollieren und zurückkehren.','Funktionelle Alltagsbeweglichkeit verbessern.','Bewegung aus der Hüfte.','Rücken stark runden oder zu weit gehen.','Bei Bedarf Stütze nutzen.','Bei stechendem Schmerz, Schwindel oder Gleichgewichtsverlust abbrechen.','Bei eingeschränkter Hüftbeugung oder Standfähigkeit anpassen.'),
('mobility-flexibility-calf-stretch','fr','Étirement doux du mollet','Souplesse du mollet et cheville','Debout face à un support stable.','Reculez un pied, gardez le talon au sol et avancez doucement le bassin jusqu’à une tension légère.','Entretenir la souplesse du mollet.','Tension légère, pas de douleur.','Rebondir ou forcer.','Support stable et amplitude confortable.','Arrêtez en cas de douleur vive, crampe persistante ou instabilité.','À adapter en cas de lésion récente du mollet ou tendon d’Achille.'),
('mobility-flexibility-calf-stretch','en','Gentle calf stretch','Calf and ankle flexibility','Stand facing stable support.','Step one foot back, keep the heel down, and gently shift forward until a mild stretch is felt.','Maintain calf flexibility.','Aim for mild tension, not pain.','Bouncing or forcing.','Use stable support and comfortable range.','Stop for sharp pain, persistent cramp, or instability.','Modify after recent calf or Achilles injury.'),
('mobility-flexibility-calf-stretch','de','Sanfte Wadendehnung','Waden- und Sprunggelenksbeweglichkeit','Vor stabiler Stütze stehen.','Ein Bein zurückstellen, Ferse am Boden und Becken sanft vor bis leichter Zug entsteht.','Wadenbeweglichkeit erhalten.','Leichter Zug statt Schmerz.','Federn oder erzwingen.','Stabile Stütze und angenehme Weite.','Bei stechendem Schmerz, anhaltendem Krampf oder Instabilität abbrechen.','Nach frischer Waden- oder Achillessehnenverletzung anpassen.'),
('mobility-flexibility-supported-flow','fr','Enchaînement mobilité avec appui','Mobilité globale et coordination','Debout près d’un support stable.','Enchaînez lentement petite flexion de genoux, ouverture des bras et transfert de poids.','Créer une routine globale de mobilité douce.','Restez fluide et contrôlé.','Aller vite ou utiliser une amplitude excessive.','Support à portée et environnement dégagé.','Arrêtez en cas de vertige, perte d’équilibre ou douleur vive.','À adapter si la station debout n’est pas sûre.'),
('mobility-flexibility-supported-flow','en','Supported mobility flow','Whole-body mobility and coordination','Stand near stable support.','Slowly combine a small knee bend, arm opening, and weight shift.','Create a gentle whole-body mobility routine.','Stay smooth and controlled.','Moving quickly or using excessive range.','Keep support within reach and space clear.','Stop for dizziness, loss of balance, or sharp pain.','Modify if standing is unsafe.'),
('mobility-flexibility-supported-flow','de','Unterstützter Mobilitätsfluss','Ganzkörperbeweglichkeit und Koordination','Nahe einer stabilen Stütze stehen.','Kleine Kniebeuge, Armöffnung und Gewichtsverlagerung langsam kombinieren.','Sanfte Ganzkörper-Mobilitätsroutine schaffen.','Flüssig und kontrolliert bleiben.','Zu schnell oder zu große Bewegungsweite.','Stütze erreichbar und Raum frei halten.','Bei Schwindel, Gleichgewichtsverlust oder stechendem Schmerz abbrechen.','Bei unsicherem Stand anpassen.')
) v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications) on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;
insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'full-body',true from public.exercises where stable_key in ('mobility-flexibility-breathing-reset','mobility-flexibility-thoracic-rotation','mobility-flexibility-hip-hinge','mobility-flexibility-calf-stretch','mobility-flexibility-supported-flow') on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;
insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.exercises e join (values
('mobility-flexibility-hip-hinge','hands-supported','easy',0,2,6,null::integer,30,'controlled'),('mobility-flexibility-hip-hinge','standard','standard',1,2,8,null::integer,30,'controlled'),('mobility-flexibility-hip-hinge','slower-tempo','hard',2,3,8,null::integer,45,'3-second-lowering'),
('mobility-flexibility-supported-flow','small-range','easy',0,2,4,null::integer,30,'slow-controlled'),('mobility-flexibility-supported-flow','standard-flow','standard',1,2,6,null::integer,30,'slow-controlled'),('mobility-flexibility-supported-flow','longer-flow','hard',2,3,6,null::integer,45,'slow-controlled')) v(exercise_key,stable_key,difficulty,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;
insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.tip from public.exercise_variants ev join public.exercises e on e.id=ev.exercise_id join (values
('mobility-flexibility-hip-hinge','hands-supported','fr','Charnière avec appui','Gardez les mains sur un support stable.','Petite amplitude.'),('mobility-flexibility-hip-hinge','hands-supported','en','Supported hip hinge','Keep hands on stable support.','Use a small range.'),('mobility-flexibility-hip-hinge','hands-supported','de','Hüftbeugen mit Stütze','Hände an stabiler Stütze lassen.','Kleine Weite.'),
('mobility-flexibility-hip-hinge','standard','fr','Charnière standard','Reculez les hanches puis revenez avec contrôle.','Gardez le tronc stable.'),('mobility-flexibility-hip-hinge','standard','en','Standard hip hinge','Move the hips back, then return with control.','Keep the trunk steady.'),('mobility-flexibility-hip-hinge','standard','de','Standard Hüftbeugen','Hüften zurückführen und kontrolliert zurück.','Rumpf stabil halten.'),
('mobility-flexibility-hip-hinge','slower-tempo','fr','Charnière lente','Ralentissez la descente sur environ trois secondes.','Augmentez le contrôle, pas l’amplitude.'),('mobility-flexibility-hip-hinge','slower-tempo','en','Slower hip hinge','Slow the lowering phase to about three seconds.','Increase control, not range.'),('mobility-flexibility-hip-hinge','slower-tempo','de','Langsames Hüftbeugen','Absenken über etwa drei Sekunden.','Kontrolle statt Weite steigern.'),
('mobility-flexibility-supported-flow','small-range','fr','Flow petite amplitude','Utilisez de très petits mouvements.','Idéal pour commencer.'),('mobility-flexibility-supported-flow','small-range','en','Small-range flow','Use very small movements.','Good starting option.'),('mobility-flexibility-supported-flow','small-range','de','Flow kleine Weite','Sehr kleine Bewegungen nutzen.','Guter Einstieg.'),
('mobility-flexibility-supported-flow','standard-flow','fr','Flow standard','Enchaînez les mouvements à vitesse lente.','Restez fluide.'),('mobility-flexibility-supported-flow','standard-flow','en','Standard flow','Link the movements at a slow pace.','Keep it smooth.'),('mobility-flexibility-supported-flow','standard-flow','de','Standard Flow','Bewegungen langsam verbinden.','Flüssig bleiben.'),
('mobility-flexibility-supported-flow','longer-flow','fr','Flow prolongé','Prolongez la séquence si bien tolérée.','Augmentez la durée.'),('mobility-flexibility-supported-flow','longer-flow','en','Longer flow','Extend the sequence if well tolerated.','Increase duration.'),('mobility-flexibility-supported-flow','longer-flow','de','Längerer Flow','Sequenz bei guter Verträglichkeit verlängern.','Dauer steigern.')) t(exercise_key,variant_key,language,name,instructions,tip) on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;