insert into public.exercises (
  stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable
) values
('spine-back-breathing-brace','draft','1.0.0',2,6,5,20,5,'slow-controlled',false),
('spine-back-pelvic-tilt','draft','1.0.0',2,10,0,20,5,'slow-controlled',false),
('spine-back-knee-roll','draft','1.0.0',2,8,0,20,5,'slow-controlled',false),
('spine-back-quadruped-rock-back','draft','1.0.0',2,8,0,30,4,'slow-controlled',false),
('spine-back-quadruped-stability','draft','1.0.0',3,6,3,30,3,'controlled',false)
on conflict (stable_key) do update set
  status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,
  default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,
  default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,
  default_tempo=excluded.default_tempo;

insert into public.exercise_translations (
  exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications
)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('spine-back-breathing-brace','fr','Respiration et gainage doux','Respiration, contrôle abdominal et stabilité du tronc','Allongé sur le dos, genoux pliés si confortable, épaules relâchées.','Inspirez calmement puis, en expirant, engagez légèrement la paroi abdominale sans bloquer la respiration. Maintenez quelques secondes puis relâchez.','Améliorer le contrôle du tronc avec une charge très faible.','L’effort doit être léger et compatible avec une respiration normale.','Bloquer la respiration, pousser fortement le ventre vers l’intérieur ou contracter tout le corps.','Restez dans une position confortable et évitez toute poussée maximale.','Arrêtez en cas de douleur vive, douleur irradiée qui augmente nettement, faiblesse ou engourdissement nouveaux, malaise ou autre symptôme inquiétant.','À adapter si la position allongée est mal tolérée ou si une restriction postopératoire du tronc a été prescrite.'),
('spine-back-breathing-brace','en','Breathing with gentle brace','Breathing, abdominal control, and trunk stability','Lie on your back with knees bent if comfortable and shoulders relaxed.','Breathe in calmly, then as you breathe out gently engage the abdominal wall without holding your breath. Hold briefly, then relax.','Improve trunk control with very low loading.','Keep the effort light and compatible with normal breathing.','Holding the breath, pulling the abdomen in forcefully, or tensing the whole body.','Stay in a comfortable position and avoid maximal bracing.','Stop for sharp pain, clearly increasing radiating pain, new weakness or numbness, dizziness, or another concerning symptom.','Modify if lying is poorly tolerated or if post-operative trunk restrictions have been prescribed.'),
('spine-back-breathing-brace','de','Atmung mit sanfter Rumpfspannung','Atmung, Bauchkontrolle und Rumpfstabilität','Liegen Sie auf dem Rücken, Knie wenn angenehm gebeugt, Schultern entspannt.','Atmen Sie ruhig ein und spannen Sie beim Ausatmen die Bauchwand leicht an, ohne die Luft anzuhalten. Kurz halten, dann lösen.','Rumpfkontrolle mit sehr geringer Belastung verbessern.','Die Anspannung soll leicht bleiben und normales Atmen erlauben.','Luft anhalten, Bauch stark einziehen oder den ganzen Körper verspannen.','Bequeme Position wählen und maximale Anspannung vermeiden.','Bei stechendem Schmerz, deutlich zunehmender Ausstrahlung, neuer Schwäche oder Taubheit, Schwindel oder anderen bedenklichen Symptomen abbrechen.','Bei schlecht tolerierter Rückenlage oder postoperativen Rumpfeinschränkungen anpassen.'),
('spine-back-pelvic-tilt','fr','Bascule douce du bassin','Mobilité lombaire douce et contrôle lombo-pelvien','Allongé sur le dos, genoux pliés et pieds posés si confortable.','Faites rouler très légèrement le bassin pour modifier la courbure du bas du dos, puis revenez à une position neutre.','Entretenir une mobilité contrôlée du bas du dos et du bassin.','Le mouvement doit être petit et fluide.','Forcer l’amplitude, pousser avec les jambes ou chercher à aplatir fortement le dos.','Utilisez uniquement une amplitude confortable.','Arrêtez si la douleur s’intensifie nettement, si des symptômes descendent davantage dans la jambe, ou en cas de faiblesse, engourdissement nouveau ou malaise.','À adapter après chirurgie récente ou si la flexion/extension lombaire est temporairement limitée.'),
('spine-back-pelvic-tilt','en','Gentle pelvic tilt','Gentle lumbar mobility and lumbopelvic control','Lie on your back with knees bent and feet supported if comfortable.','Very gently roll the pelvis to slightly change the curve of the lower back, then return to neutral.','Maintain controlled lower-back and pelvic mobility.','Keep the movement small and smooth.','Forcing range, pushing strongly through the legs, or trying to flatten the back aggressively.','Use only a comfortable range.','Stop if pain clearly intensifies, symptoms travel further down the leg, or new weakness, numbness, or dizziness develops.','Modify after recent surgery or when lumbar flexion/extension is temporarily restricted.'),
('spine-back-pelvic-tilt','de','Sanfte Beckenkippung','Sanfte Lendenbeweglichkeit und lumbopelvine Kontrolle','Liegen Sie auf dem Rücken, Knie gebeugt und Füße aufgestellt, wenn angenehm.','Kippen Sie das Becken sehr leicht, sodass sich die Lendenkrümmung etwas verändert, und kehren Sie zur Neutralstellung zurück.','Kontrollierte Beweglichkeit von Lendenwirbelsäule und Becken erhalten.','Bewegung klein und flüssig halten.','Bewegungsweite erzwingen, stark über die Beine drücken oder den Rücken aggressiv flach drücken.','Nur einen angenehmen Bewegungsbereich verwenden.','Abbrechen, wenn Schmerzen deutlich zunehmen, Symptome weiter ins Bein ziehen oder neue Schwäche, Taubheit oder Schwindel auftreten.','Nach frischer Operation oder bei vorübergehend begrenzter Lendenbeugung/-streckung anpassen.'),
('spine-back-knee-roll','fr','Roulement contrôlé des genoux','Mobilité douce du tronc et contrôle rotatoire','Allongé sur le dos, genoux pliés et pieds au sol, amplitude confortable.','Laissez les genoux se déplacer légèrement ensemble d’un côté puis revenez au centre et changez de côté.','Entretenir une rotation douce du tronc sans charge élevée.','Gardez les épaules détendues et utilisez une petite amplitude.','Laisser tomber les jambes rapidement, forcer la rotation ou provoquer une douleur irradiée.','Le mouvement doit rester lent et confortable.','Arrêtez en cas de douleur vive, augmentation nette d’une douleur irradiée, faiblesse ou engourdissement nouveau.','À éviter ou modifier si la rotation du tronc est médicalement limitée ou après certaines interventions récentes.'),
('spine-back-knee-roll','en','Controlled knee roll','Gentle trunk mobility and rotational control','Lie on your back with knees bent and feet supported in a comfortable position.','Let both knees move a short distance to one side, return to center, then repeat to the other side.','Maintain gentle trunk rotation without high loading.','Keep the shoulders relaxed and use a small range.','Dropping the legs quickly, forcing rotation, or provoking radiating pain.','Keep the movement slow and comfortable.','Stop for sharp pain, clearly increasing radiating pain, or new weakness or numbness.','Avoid or modify if trunk rotation is medically restricted or after certain recent procedures.'),
('spine-back-knee-roll','de','Kontrolliertes Knierollen','Sanfte Rumpfbeweglichkeit und Rotationskontrolle','Liegen Sie auf dem Rücken, Knie gebeugt und Füße aufgestellt in angenehmer Position.','Bewegen Sie beide Knie ein kleines Stück gemeinsam zu einer Seite, zurück zur Mitte und dann zur anderen Seite.','Sanfte Rumpfrotation ohne hohe Belastung erhalten.','Schultern entspannt halten und kleine Bewegungsweite nutzen.','Beine schnell fallen lassen, Rotation erzwingen oder Ausstrahlung provozieren.','Bewegung langsam und angenehm halten.','Bei stechendem Schmerz, deutlich zunehmender Ausstrahlung oder neuer Schwäche bzw. Taubheit abbrechen.','Bei medizinisch eingeschränkter Rumpfrotation oder nach bestimmten frischen Eingriffen vermeiden oder anpassen.'),
('spine-back-quadruped-rock-back','fr','Recul contrôlé à quatre pattes','Mobilité des hanches et contrôle du tronc en appui','À quatre pattes, mains sous les épaules et genoux sous les hanches, si cette position est confortable.','Gardez le tronc stable et reculez doucement le bassin vers les talons sur une courte distance, puis revenez.','Travailler une mobilité fonctionnelle avec contrôle du tronc et des hanches.','Cherchez un mouvement confortable, pas une grande amplitude.','Arrondir ou creuser fortement le dos, aller trop loin ou forcer malgré les symptômes.','Utilisez une surface stable et une amplitude tolérée.','Arrêtez en cas de douleur vive, douleur irradiée qui augmente, faiblesse ou engourdissement nouveau, ou douleur importante aux poignets/genoux.','À éviter si la position à quatre pattes est contre-indiquée ou mal tolérée.'),
('spine-back-quadruped-rock-back','en','Quadruped rock-back','Hip mobility and trunk control in supported position','Start on hands and knees with hands under shoulders and knees under hips if comfortable.','Keep the trunk steady and gently move the hips back a short distance toward the heels, then return.','Practice functional mobility with trunk and hip control.','Aim for comfort rather than large range.','Strongly rounding or arching the back, moving too far, or pushing through symptoms.','Use a stable surface and a tolerated range.','Stop for sharp pain, increasing radiating pain, new weakness or numbness, or significant wrist/knee pain.','Avoid if the hands-and-knees position is contraindicated or poorly tolerated.'),
('spine-back-quadruped-rock-back','de','Kontrolliertes Zurückverlagern im Vierfüßlerstand','Hüftbeweglichkeit und Rumpfkontrolle in Stützposition','Beginnen Sie im Vierfüßlerstand mit Händen unter den Schultern und Knien unter den Hüften, wenn angenehm.','Halten Sie den Rumpf stabil und schieben Sie das Becken ein kleines Stück Richtung Fersen, dann zurück.','Funktionelle Beweglichkeit mit Rumpf- und Hüftkontrolle üben.','Komfort ist wichtiger als große Bewegungsweite.','Rücken stark runden oder überstrecken, zu weit bewegen oder Beschwerden erzwingen.','Stabile Unterlage und verträgliche Bewegungsweite verwenden.','Bei stechendem Schmerz, zunehmender Ausstrahlung, neuer Schwäche oder Taubheit oder deutlichen Handgelenk-/Knieschmerzen abbrechen.','Bei kontraindiziertem oder schlecht toleriertem Vierfüßlerstand vermeiden.'),
('spine-back-quadruped-stability','fr','Stabilité du tronc à quatre pattes','Contrôle du tronc et stabilité lombo-pelvienne','À quatre pattes sur une surface stable, tronc dans une position confortable.','Maintenez une légère activation du tronc puis déchargez lentement une main ou faites glisser une jambe vers l’arrière selon la variante, sans tourner le bassin.','Développer progressivement la stabilité du tronc avec une charge contrôlée.','Le bassin doit rester aussi stable que possible.','Tourner le bassin, lever trop haut, bloquer la respiration ou aller trop vite.','Commencez par une variante facile et gardez une respiration normale.','Arrêtez en cas de douleur vive, augmentation d’une irradiation, faiblesse ou engourdissement nouveau, perte de contrôle ou malaise.','À éviter si la position à quatre pattes ou la mise en charge des membres est contre-indiquée.'),
('spine-back-quadruped-stability','en','Quadruped trunk stability','Trunk control and lumbopelvic stability','Start on hands and knees on a stable surface with the trunk in a comfortable position.','Gently brace the trunk, then slowly unload one hand or slide one leg back depending on the variation, without rotating the pelvis.','Progressively develop trunk stability with controlled loading.','Keep the pelvis as steady as possible.','Rotating the pelvis, lifting too high, holding the breath, or moving too quickly.','Start with an easy variation and keep breathing normally.','Stop for sharp pain, increasing radiating pain, new weakness or numbness, loss of control, or dizziness.','Avoid if quadruped positioning or limb loading is contraindicated.'),
('spine-back-quadruped-stability','de','Rumpfstabilität im Vierfüßlerstand','Rumpfkontrolle und lumbopelvine Stabilität','Beginnen Sie auf stabiler Unterlage im Vierfüßlerstand mit angenehm positioniertem Rumpf.','Spannen Sie den Rumpf leicht an und entlasten Sie je nach Variante langsam eine Hand oder schieben Sie ein Bein nach hinten, ohne das Becken zu drehen.','Rumpfstabilität mit kontrollierter Belastung schrittweise entwickeln.','Becken möglichst ruhig halten.','Becken drehen, zu hoch anheben, Luft anhalten oder zu schnell bewegen.','Mit leichter Variante beginnen und normal weiteratmen.','Bei stechendem Schmerz, zunehmender Ausstrahlung, neuer Schwäche oder Taubheit, Kontrollverlust oder Schwindel abbrechen.','Bei kontraindiziertem Vierfüßlerstand oder nicht erlaubter Extremitätenbelastung vermeiden.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set
  name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,
  why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,
  safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'spine-back',true from public.exercises
where stable_key in ('spine-back-breathing-brace','spine-back-pelvic-tilt','spine-back-knee-roll','spine-back-quadruped-rock-back','spine-back-quadruped-stability')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('spine-back-quadruped-rock-back','small-range','easy',0,2,6,null,30,'slow-controlled'),
('spine-back-quadruped-rock-back','standard-range','standard',1,2,8,null,30,'slow-controlled'),
('spine-back-quadruped-rock-back','longer-range-controlled','hard',2,3,8,null,45,'slow-controlled'),
('spine-back-quadruped-stability','hand-unweighting','easy',0,3,6,2,30,'controlled'),
('spine-back-quadruped-stability','leg-slide','standard',1,3,6,3,30,'controlled'),
('spine-back-quadruped-stability','opposite-arm-leg','hard',2,3,6,3,45,'controlled')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set
  difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,
  sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,
  hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,
  tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('spine-back-quadruped-rock-back','small-range','fr','Recul de petite amplitude','Déplacez le bassin seulement de quelques centimètres vers l’arrière puis revenez.','Choisissez cette variante si la position est nouvelle ou sensible.'),
('spine-back-quadruped-rock-back','small-range','en','Small-range rock-back','Move the hips back only a short distance, then return.','Use this option when the position is new or sensitive.'),
('spine-back-quadruped-rock-back','small-range','de','Zurückverlagern klein','Becken nur wenige Zentimeter nach hinten bewegen und zurückkehren.','Diese Variante bei neuer oder empfindlicher Position wählen.'),
('spine-back-quadruped-rock-back','standard-range','fr','Recul contrôlé standard','Reculez le bassin dans une amplitude confortable tout en gardant le tronc contrôlé.','Gardez une vitesse lente et régulière.'),
('spine-back-quadruped-rock-back','standard-range','en','Standard controlled rock-back','Move the hips back through a comfortable range while keeping trunk control.','Keep the speed slow and steady.'),
('spine-back-quadruped-rock-back','standard-range','de','Standard kontrolliertes Zurückverlagern','Becken in angenehmer Bewegungsweite nach hinten bewegen und Rumpf kontrollieren.','Langsam und gleichmäßig bewegen.'),
('spine-back-quadruped-rock-back','longer-range-controlled','fr','Recul contrôlé amplitude augmentée','Augmentez légèrement l’amplitude seulement si la version standard est bien tolérée.','Augmentez l’amplitude avant d’augmenter la vitesse.'),
('spine-back-quadruped-rock-back','longer-range-controlled','en','Controlled longer-range rock-back','Increase the range slightly only when the standard version is well tolerated.','Increase range before speed.'),
('spine-back-quadruped-rock-back','longer-range-controlled','de','Kontrolliertes Zurückverlagern größere Weite','Bewegungsweite nur leicht erhöhen, wenn die Standardvariante gut vertragen wird.','Zuerst Weite, nicht Geschwindigkeit steigern.'),
('spine-back-quadruped-stability','hand-unweighting','fr','Décharge d’une main','Allégez une main ou décollez-la très légèrement tout en gardant le bassin stable.','Commencez par de très petits changements d’appui.'),
('spine-back-quadruped-stability','hand-unweighting','en','Hand unweighting','Lightly unload one hand or lift it just off the surface while keeping the pelvis steady.','Start with very small changes in support.'),
('spine-back-quadruped-stability','hand-unweighting','de','Eine Hand entlasten','Eine Hand leicht entlasten oder minimal anheben und Becken stabil halten.','Mit sehr kleinen Stützveränderungen beginnen.'),
('spine-back-quadruped-stability','leg-slide','fr','Glissement d’une jambe','Faites glisser une jambe vers l’arrière sans la lever haut et sans tourner le bassin.','Gardez le mouvement long et bas.'),
('spine-back-quadruped-stability','leg-slide','en','Leg slide','Slide one leg backward without lifting it high and without rotating the pelvis.','Keep the movement long and low.'),
('spine-back-quadruped-stability','leg-slide','de','Beingleiten nach hinten','Ein Bein nach hinten schieben, ohne es hoch anzuheben oder das Becken zu drehen.','Bewegung lang und niedrig halten.'),
('spine-back-quadruped-stability','opposite-arm-leg','fr','Bras et jambe opposés','Allongez progressivement un bras et la jambe opposée seulement si vous pouvez garder le tronc stable.','La stabilité est prioritaire sur la hauteur.'),
('spine-back-quadruped-stability','opposite-arm-leg','en','Opposite arm and leg','Gradually reach one arm and the opposite leg only if you can keep the trunk steady.','Stability matters more than height.'),
('spine-back-quadruped-stability','opposite-arm-leg','de','Gegenüberliegender Arm und Bein','Arm und gegenüberliegendes Bein nur strecken, wenn der Rumpf stabil bleibt.','Stabilität ist wichtiger als Höhe.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;