insert into public.exercises (
  stable_key,status,clinical_version,default_sets,default_repetitions,default_hold_seconds,default_rest_seconds,default_frequency_per_week,default_tempo,motion_trackable
) values
('hip-pelvis-glute-set','draft','1.0.0',3,10,5,30,5,'isometric',false),
('hip-pelvis-heel-slide','draft','1.0.0',2,10,0,30,5,'slow-controlled',false),
('hip-pelvis-bridge','draft','1.0.0',3,8,0,45,3,'controlled',false),
('hip-pelvis-supported-abduction','draft','1.0.0',3,8,0,45,3,'controlled',false),
('hip-pelvis-supported-weight-shift','draft','1.0.0',3,8,0,30,4,'slow-controlled',false)
on conflict (stable_key) do update set
  status=excluded.status,clinical_version=excluded.clinical_version,default_sets=excluded.default_sets,
  default_repetitions=excluded.default_repetitions,default_hold_seconds=excluded.default_hold_seconds,
  default_rest_seconds=excluded.default_rest_seconds,default_frequency_per_week=excluded.default_frequency_per_week,
  default_tempo=excluded.default_tempo;

insert into public.exercise_translations (
  exercise_id,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications
)
select e.id,v.language,v.name,v.target,v.starting_position,v.movement,v.why_this_exercise,v.main_tip,v.common_mistakes,v.safety_instructions,v.stop_criteria,v.contraindications
from public.exercises e
join (values
('hip-pelvis-glute-set','fr','Contraction des fessiers','Activation des muscles fessiers et contrôle du bassin','Allongé sur le dos ou assis confortablement, bassin en position neutre.','Contractez doucement les fessiers, maintenez quelques secondes puis relâchez sans retenir votre respiration.','Réactiver les fessiers avec une charge faible et préparer les exercices fonctionnels.','Contractez sans serrer excessivement ni cambrer le dos.','Bloquer la respiration, pousser avec les pieds ou cambrer fortement le bas du dos.','Le mouvement doit rester doux et confortable. Après une chirurgie récente de hanche, respectez strictement les consignes de votre équipe soignante.','Arrêtez en cas de douleur vive, sensation de luxation, malaise ou réaction inhabituelle.','À adapter ou éviter si une contraction active de la hanche ou du bassin est temporairement limitée par une consigne médicale.'),
('hip-pelvis-glute-set','en','Gluteal set','Glute activation and pelvic control','Lie on your back or sit comfortably with the pelvis in a neutral position.','Gently tighten the buttock muscles, hold for a few seconds, then relax without holding your breath.','Reactivate the gluteal muscles with low load and prepare for functional exercise.','Tighten gently without excessive squeezing or arching the back.','Holding the breath, pushing strongly through the feet, or over-arching the lower back.','Keep the effort gentle and comfortable. After recent hip surgery, strictly follow your treating team’s precautions.','Stop for sharp pain, a feeling of dislocation, dizziness, or another unusual reaction.','Modify or avoid when active hip or pelvic contraction is temporarily restricted by medical advice.'),
('hip-pelvis-glute-set','de','Gesäßmuskel-Anspannung','Aktivierung der Gesäßmuskulatur und Beckenkontrolle','Liegen Sie auf dem Rücken oder sitzen Sie bequem mit neutraler Beckenposition.','Spannen Sie die Gesäßmuskeln sanft an, halten Sie einige Sekunden und lösen Sie wieder, ohne die Luft anzuhalten.','Gesäßmuskulatur mit geringer Belastung aktivieren und funktionelle Übungen vorbereiten.','Sanft anspannen, ohne übermäßig zu pressen oder den Rücken zu überstrecken.','Luft anhalten, stark über die Füße drücken oder den unteren Rücken stark ins Hohlkreuz bringen.','Die Anspannung soll sanft und angenehm bleiben. Nach einer frischen Hüftoperation gelten strikt die Vorgaben des Behandlungsteams.','Bei stechendem Schmerz, Luxationsgefühl, Schwindel oder anderer ungewöhnlicher Reaktion abbrechen.','Bei vorübergehender medizinischer Einschränkung aktiver Hüft- oder Beckenbewegung anpassen oder vermeiden.'),
('hip-pelvis-heel-slide','fr','Glissement du talon pour la hanche','Mobilité douce de hanche en flexion-extension','Allongé sur le dos, jambe détendue, talon posé sur une surface glissante.','Faites glisser lentement le talon vers vous pour plier la hanche et le genou dans une amplitude confortable, puis revenez.','Entretenir une mobilité douce de la hanche sans charge importante.','Restez dans l’amplitude autorisée et confortable.','Forcer l’amplitude, tourner la jambe de façon excessive ou aller vite.','Après une chirurgie de hanche, ne dépassez jamais les restrictions de mouvement données par l’équipe soignante.','Arrêtez en cas de douleur vive, blocage, sensation d’instabilité ou augmentation nette des symptômes.','À éviter ou modifier si la flexion de hanche est limitée, notamment après certaines interventions chirurgicales.'),
('hip-pelvis-heel-slide','en','Hip heel slide','Gentle hip flexion-extension mobility','Lie on your back with the leg relaxed and the heel on a surface that allows sliding.','Slowly slide the heel toward you to bend the hip and knee within a comfortable range, then return.','Maintain gentle hip mobility without high loading.','Stay within the allowed and comfortable range.','Forcing the range, excessively rotating the leg, or moving too quickly.','After hip surgery, never exceed movement restrictions provided by the treating team.','Stop for sharp pain, locking, a feeling of instability, or a clear increase in symptoms.','Avoid or modify when hip flexion is restricted, including after some surgical procedures.'),
('hip-pelvis-heel-slide','de','Fersengleiten für die Hüfte','Sanfte Hüftbeweglichkeit in Beugung und Streckung','Legen Sie sich auf den Rücken, das Bein entspannt, die Ferse auf einer gleitfähigen Unterlage.','Ziehen Sie die Ferse langsam zu sich, sodass Hüfte und Knie sich in einem angenehmen Bereich beugen, und gleiten Sie wieder zurück.','Sanfte Hüftbeweglichkeit ohne hohe Belastung erhalten.','Im erlaubten und angenehmen Bewegungsbereich bleiben.','Bewegungsweite erzwingen, Bein stark drehen oder zu schnell bewegen.','Nach einer Hüftoperation niemals die vom Behandlungsteam vorgegebenen Bewegungsgrenzen überschreiten.','Bei stechendem Schmerz, Blockieren, Instabilitätsgefühl oder deutlicher Beschwerdezunahme abbrechen.','Bei eingeschränkter Hüftbeugung, insbesondere nach bestimmten Operationen, vermeiden oder anpassen.'),
('hip-pelvis-bridge','fr','Pont fessier','Force des fessiers, chaîne postérieure et contrôle du bassin','Allongé sur le dos, genoux pliés si confortable, pieds posés au sol.','Contractez doucement les fessiers puis soulevez le bassin de quelques centimètres, gardez le tronc stable et redescendez avec contrôle.','Développer la force des fessiers et le contrôle du bassin.','Montez seulement aussi haut que vous pouvez le faire sans douleur ni compensation.','Cambrer excessivement le dos, pousser trop fort ou laisser les genoux s’effondrer.','Le pont doit rester confortable. En postopératoire de hanche, utilisez-le uniquement si cette position et ce mouvement sont autorisés.','Arrêtez en cas de douleur vive, crampe persistante, sensation d’instabilité ou autre symptôme inquiétant.','Peut être inadapté en phase postopératoire précoce ou lorsque l’appui/extension de hanche est limité.'),
('hip-pelvis-bridge','en','Glute bridge','Glute strength, posterior-chain support and pelvic control','Lie on your back with knees bent if comfortable and feet on the floor.','Gently tighten the glutes, lift the pelvis a short distance, keep the trunk steady, then lower with control.','Build glute strength and pelvic control.','Lift only as high as you can without pain or compensation.','Over-arching the back, pushing too hard, or letting the knees collapse inward.','Keep the bridge comfortable. After hip surgery, use only if this position and movement are allowed.','Stop for sharp pain, persistent cramping, instability, or another concerning symptom.','May be unsuitable early after surgery or when hip loading or extension is restricted.'),
('hip-pelvis-bridge','de','Gesäßbrücke','Gesäßkraft, hintere Kette und Beckenkontrolle','Liegen Sie auf dem Rücken, Knie wenn angenehm gebeugt, Füße am Boden.','Spannen Sie die Gesäßmuskeln sanft an, heben Sie das Becken etwas an, halten Sie den Rumpf stabil und senken Sie kontrolliert ab.','Gesäßkraft und Beckenkontrolle aufbauen.','Nur so hoch heben, wie es ohne Schmerz oder Ausweichbewegung möglich ist.','Rücken überstrecken, zu stark drücken oder Knie nach innen kippen lassen.','Die Brücke soll angenehm bleiben. Nach Hüftoperation nur verwenden, wenn Position und Bewegung erlaubt sind.','Bei stechendem Schmerz, anhaltendem Krampf, Instabilität oder anderen bedenklichen Symptomen abbrechen.','Kann früh nach Operationen oder bei eingeschränkter Hüftbelastung bzw. -streckung ungeeignet sein.'),
('hip-pelvis-supported-abduction','fr','Abduction de hanche avec appui','Moyen fessier et contrôle latéral du bassin','Debout près d’un support stable, poids réparti confortablement.','Gardez le tronc droit et déplacez doucement une jambe sur le côté sans tourner le pied excessivement, puis revenez.','Renforcer progressivement les muscles latéraux de la hanche utiles à la stabilité du bassin.','Faites un petit mouvement propre plutôt qu’un grand mouvement compensé.','Incliner le tronc, tourner la hanche ou lever la jambe trop haut.','Utilisez un support stable. Après chirurgie de hanche, respectez les restrictions de mouvement et d’appui prescrites.','Arrêtez en cas de douleur vive, perte d’équilibre, sensation d’instabilité ou augmentation nette des symptômes.','À éviter ou adapter si l’abduction, l’appui ou la position debout sont limités médicalement.'),
('hip-pelvis-supported-abduction','en','Supported hip abduction','Gluteus medius and lateral pelvic control','Stand near a stable support with weight comfortably distributed.','Keep the trunk upright and gently move one leg out to the side without excessive foot rotation, then return.','Progressively strengthen the lateral hip muscles used for pelvic stability.','Use a small clean movement rather than a large compensated one.','Leaning the trunk, rotating the hip, or lifting the leg too high.','Use stable support. After hip surgery, follow prescribed movement and weight-bearing restrictions.','Stop for sharp pain, loss of balance, instability, or a clear increase in symptoms.','Avoid or modify when abduction, weight bearing, or standing is medically restricted.'),
('hip-pelvis-supported-abduction','de','Hüftabduktion mit Unterstützung','Gluteus medius und seitliche Beckenkontrolle','Stehen Sie nahe einer stabilen Stütze mit angenehm verteiltem Gewicht.','Halten Sie den Oberkörper aufrecht und führen Sie ein Bein sanft zur Seite, ohne den Fuß stark zu drehen, dann zurück.','Seitliche Hüftmuskulatur für Beckenstabilität schrittweise kräftigen.','Lieber eine kleine saubere als eine große kompensierte Bewegung.','Oberkörper neigen, Hüfte drehen oder Bein zu hoch anheben.','Stabile Stütze verwenden. Nach Hüftoperation gelten die verordneten Bewegungs- und Belastungsgrenzen.','Bei stechendem Schmerz, Gleichgewichtsverlust, Instabilität oder deutlicher Beschwerdezunahme abbrechen.','Bei medizinisch eingeschränkter Abduktion, Belastung oder Standfähigkeit vermeiden oder anpassen.'),
('hip-pelvis-supported-weight-shift','fr','Transfert de poids avec appui','Tolérance à l’appui, contrôle du bassin et préparation à la marche','Debout avec les deux pieds au sol et les mains près d’un support stable.','Déplacez lentement une petite partie du poids d’un côté vers l’autre sans décoller les pieds, puis revenez au centre.','Préparer progressivement la mise en charge et le contrôle nécessaires à la marche.','Commencez par de petits transferts, sans chercher l’amplitude maximale.','Déplacer le bassin trop loin, lâcher l’appui trop tôt ou provoquer une douleur.','Utilisez un support stable. Respectez toute restriction médicale de mise en charge.','Arrêtez en cas de douleur vive, vertige, perte d’équilibre ou sensation d’instabilité importante.','À éviter si la mise en charge n’est pas autorisée ou si la station debout n’est pas sûre sans assistance.'),
('hip-pelvis-supported-weight-shift','en','Supported weight shift','Weight-bearing tolerance, pelvic control and walking preparation','Stand with both feet on the floor and hands near a stable support.','Slowly shift a small amount of weight from one side to the other without lifting the feet, then return to center.','Gradually prepare weight bearing and control needed for walking.','Start with small shifts rather than maximum range.','Shifting too far, removing support too early, or provoking pain.','Use stable support and respect any medical weight-bearing restriction.','Stop for sharp pain, dizziness, loss of balance, or marked instability.','Avoid when weight bearing is not allowed or standing is not safe without assistance.'),
('hip-pelvis-supported-weight-shift','de','Gewichtsverlagerung mit Unterstützung','Belastungsverträglichkeit, Beckenkontrolle und Gehvorbereitung','Stehen Sie mit beiden Füßen am Boden und den Händen nahe einer stabilen Stütze.','Verlagern Sie langsam einen kleinen Teil des Gewichts von einer Seite zur anderen, ohne die Füße anzuheben, und kehren Sie zur Mitte zurück.','Belastung und Kontrolle für das Gehen schrittweise vorbereiten.','Mit kleinen Gewichtsverlagerungen beginnen statt maximaler Bewegung.','Becken zu weit verlagern, Unterstützung zu früh lösen oder Schmerz provozieren.','Stabile Stütze verwenden und medizinische Belastungseinschränkungen beachten.','Bei stechendem Schmerz, Schwindel, Gleichgewichtsverlust oder deutlicher Instabilität abbrechen.','Bei Belastungsverbot oder unsicherem Stand ohne Hilfe vermeiden.')
) as v(stable_key,language,name,target,starting_position,movement,why_this_exercise,main_tip,common_mistakes,safety_instructions,stop_criteria,contraindications)
on e.stable_key=v.stable_key
on conflict (exercise_id,language) do update set
  name=excluded.name,target=excluded.target,starting_position=excluded.starting_position,movement=excluded.movement,
  why_this_exercise=excluded.why_this_exercise,main_tip=excluded.main_tip,common_mistakes=excluded.common_mistakes,
  safety_instructions=excluded.safety_instructions,stop_criteria=excluded.stop_criteria,contraindications=excluded.contraindications;

insert into public.exercise_body_regions (exercise_id,body_region_key,is_primary)
select id,'hip-pelvis',true from public.exercises
where stable_key in ('hip-pelvis-glute-set','hip-pelvis-heel-slide','hip-pelvis-bridge','hip-pelvis-supported-abduction','hip-pelvis-supported-weight-shift')
on conflict (exercise_id,body_region_key) do update set is_primary=excluded.is_primary;

insert into public.exercise_variants (exercise_id,stable_key,difficulty,sort_order,status,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select e.id,v.stable_key,v.difficulty,v.sort_order,'draft',v.sets_override,v.repetitions_override,v.hold_seconds_override,v.rest_seconds_override,v.tempo_override
from public.exercises e
join (values
('hip-pelvis-bridge','glute-set-only','easy',0,3,8,5,45,'isometric'),
('hip-pelvis-bridge','short-range-bridge','standard',1,3,8,null,45,'controlled'),
('hip-pelvis-bridge','slow-lowering-bridge','hard',2,3,8,null,60,'3-second-lowering'),
('hip-pelvis-supported-abduction','small-range-supported','easy',0,3,6,null,45,'controlled'),
('hip-pelvis-supported-abduction','standard-supported','standard',1,3,8,null,45,'controlled'),
('hip-pelvis-supported-abduction','reduced-support','hard',2,3,8,null,60,'slow-controlled')
) as v(exercise_key,stable_key,difficulty,sort_order,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
on e.stable_key=v.exercise_key
on conflict (exercise_id,stable_key) do update set
  difficulty=excluded.difficulty,sort_order=excluded.sort_order,status=excluded.status,
  sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,
  hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,
  tempo_override=excluded.tempo_override;

insert into public.exercise_variant_translations (variant_id,language,name,instructions,coaching_tip)
select ev.id,t.language,t.name,t.instructions,t.coaching_tip
from public.exercise_variants ev
join public.exercises e on e.id=ev.exercise_id
join (values
('hip-pelvis-bridge','glute-set-only','fr','Contraction fessière sans pont','Contractez les fessiers sans soulever le bassin.','Utilisez cette variante lorsque le pont n’est pas encore approprié ou confortable.'),
('hip-pelvis-bridge','glute-set-only','en','Glute set without bridge','Tighten the glutes without lifting the pelvis.','Use this option when bridging is not yet appropriate or comfortable.'),
('hip-pelvis-bridge','glute-set-only','de','Gesäßanspannung ohne Brücke','Gesäßmuskeln anspannen, ohne das Becken anzuheben.','Diese Variante verwenden, wenn die Brücke noch nicht passend oder angenehm ist.'),
('hip-pelvis-bridge','short-range-bridge','fr','Pont de faible amplitude','Soulevez le bassin seulement de quelques centimètres puis redescendez lentement.','La qualité du contrôle est prioritaire sur la hauteur.'),
('hip-pelvis-bridge','short-range-bridge','en','Short-range bridge','Lift the pelvis only a short distance, then lower slowly.','Control quality matters more than height.'),
('hip-pelvis-bridge','short-range-bridge','de','Brücke mit kleiner Bewegungsweite','Becken nur etwas anheben und langsam wieder absenken.','Kontrollqualität ist wichtiger als Höhe.'),
('hip-pelvis-bridge','slow-lowering-bridge','fr','Pont avec descente lente','Montez de façon contrôlée puis redescendez sur environ trois secondes.','Augmentez le contrôle avant d’augmenter l’amplitude.'),
('hip-pelvis-bridge','slow-lowering-bridge','en','Bridge with slow lowering','Lift with control, then lower over about three seconds.','Increase control before increasing range.'),
('hip-pelvis-bridge','slow-lowering-bridge','de','Brücke mit langsamem Absenken','Kontrolliert anheben und über etwa drei Sekunden absenken.','Zuerst Kontrolle, dann Bewegungsweite steigern.'),
('hip-pelvis-supported-abduction','small-range-supported','fr','Abduction petite amplitude avec appui','Déplacez la jambe de quelques centimètres sur le côté avec un support stable.','Commencez petit et gardez le bassin stable.'),
('hip-pelvis-supported-abduction','small-range-supported','en','Small-range supported abduction','Move the leg only a short distance to the side while using stable support.','Start small and keep the pelvis steady.'),
('hip-pelvis-supported-abduction','small-range-supported','de','Hüftabduktion klein mit Stütze','Bein nur wenige Zentimeter zur Seite führen und stabile Stütze nutzen.','Klein beginnen und Becken stabil halten.'),
('hip-pelvis-supported-abduction','standard-supported','fr','Abduction de hanche standard avec appui','Effectuez l’abduction avec une amplitude confortable et un appui stable.','Gardez le tronc droit.'),
('hip-pelvis-supported-abduction','standard-supported','en','Standard supported hip abduction','Perform hip abduction through a comfortable range with stable support.','Keep the trunk upright.'),
('hip-pelvis-supported-abduction','standard-supported','de','Standard-Hüftabduktion mit Stütze','Hüftabduktion in angenehmer Bewegungsweite mit stabiler Stütze ausführen.','Oberkörper aufrecht halten.'),
('hip-pelvis-supported-abduction','reduced-support','fr','Abduction avec appui réduit','Réduisez légèrement l’aide des mains seulement si le mouvement reste stable et confortable.','Diminuez l’appui sans sacrifier l’équilibre.'),
('hip-pelvis-supported-abduction','reduced-support','en','Hip abduction with reduced support','Slightly reduce hand support only when the movement remains stable and comfortable.','Reduce support without sacrificing balance.'),
('hip-pelvis-supported-abduction','reduced-support','de','Hüftabduktion mit weniger Unterstützung','Handstütze nur reduzieren, wenn die Bewegung stabil und angenehm bleibt.','Unterstützung reduzieren, ohne Gleichgewicht zu verlieren.')
) as t(exercise_key,variant_key,language,name,instructions,coaching_tip)
on e.stable_key=t.exercise_key and ev.stable_key=t.variant_key
on conflict (variant_id,language) do update set name=excluded.name,instructions=excluded.instructions,coaching_tip=excluded.coaching_tip;