insert into public.programme_phases (programme_id,stable_key,sort_order,status) values (12,'safe-activation',0,'draft'),(12,'function-balance',1,'draft') on conflict (programme_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status;
insert into public.programme_phase_translations (phase_id,language,name,objective)
select pp.id,v.language,v.name,v.objective from public.programme_phases pp join (values
('safe-activation','fr','Phase 1 — Activation sécurisée','Commencer par respiration, mobilité assise et transferts avec niveau d’aide adapté.'),('safe-activation','en','Phase 1 — Safe activation','Start with breathing, seated mobility, and transfers using the appropriate assistance level.'),('safe-activation','de','Phase 1 — Sichere Aktivierung','Mit Atmung, Mobilität im Sitzen und Transfers mit passender Hilfe beginnen.'),
('function-balance','fr','Phase 2 — Fonction et équilibre','Développer progressivement transfert de poids, marche et autonomie tout en respectant fatigue et restrictions.'),('function-balance','en','Phase 2 — Function and balance','Gradually build weight shifting, walking, and independence while respecting fatigue and restrictions.'),('function-balance','de','Phase 2 — Funktion und Gleichgewicht','Gewichtsverlagerung, Gehen und Selbstständigkeit schrittweise unter Beachtung von Fatigue und Einschränkungen aufbauen.')) v(phase_key,language,name,objective) on pp.programme_id=12 and pp.stable_key=v.phase_key on conflict (phase_id,language) do update set name=excluded.name,objective=excluded.objective;
insert into public.programme_sessions (phase_id,stable_key,sort_order,status,estimated_duration_minutes)
select pp.id,v.stable_key,v.sort_order,'draft',v.minutes from public.programme_phases pp join (values ('safe-activation','session-pacing-a',0,10),('safe-activation','session-transfer-b',1,12),('function-balance','session-balance-a',0,14),('function-balance','session-walking-b',1,15)) v(phase_key,stable_key,sort_order,minutes) on pp.programme_id=12 and pp.stable_key=v.phase_key on conflict (phase_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status,estimated_duration_minutes=excluded.estimated_duration_minutes;
insert into public.programme_session_translations (session_id,language,name,intro,completion_message)
select ps.id,v.language,v.name,v.intro,v.done from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-pacing-a','fr','Séance 1 — Respiration et mobilité assise','Commencez par faible intensité et observez votre tolérance.','Terminé : arrêtez avant l’épuisement.'),('session-pacing-a','en','Session 1 — Breathing and seated mobility','Start at low intensity and observe your tolerance.','Complete: stop before exhaustion.'),('session-pacing-a','de','Einheit 1 — Atmung und Mobilität im Sitzen','Mit niedriger Intensität beginnen und Verträglichkeit beobachten.','Fertig: vor Erschöpfung stoppen.'),
('session-transfer-b','fr','Séance 2 — Transferts sécurisés','Ajoutez assis-debout avec l’aide nécessaire.','Terminé : la sécurité prime sur le volume.'),('session-transfer-b','en','Session 2 — Safe transfers','Add sit-to-stand with the assistance you need.','Complete: safety matters more than volume.'),('session-transfer-b','de','Einheit 2 — Sichere Transfers','Aufstehen/Hinsetzen mit nötiger Hilfe ergänzen.','Fertig: Sicherheit vor Umfang.'),
('session-balance-a','fr','Séance 3 — Contrôle debout','Introduisez transfert de poids seulement si la station debout est sûre.','Terminé : gardez toujours le support disponible.'),('session-balance-a','en','Session 3 — Standing control','Introduce weight shifting only when standing is safe.','Complete: always keep support available.'),('session-balance-a','de','Einheit 3 — Standkontrolle','Gewichtsverlagerung nur bei sicherem Stand einführen.','Fertig: Stütze immer verfügbar halten.'),
('session-walking-b','fr','Séance 4 — Marche et fonction','Combinez transfert, équilibre et marche sur place selon vos capacités et restrictions.','Terminé : adaptez toujours la durée à la fatigue.'),('session-walking-b','en','Session 4 — Walking and function','Combine transfers, balance, and marching according to ability and restrictions.','Complete: always adapt duration to fatigue.'),('session-walking-b','de','Einheit 4 — Gehen und Funktion','Transfers, Gleichgewicht und Marschieren entsprechend Fähigkeiten und Einschränkungen kombinieren.','Fertig: Dauer immer an Fatigue anpassen.')) v(session_key,language,name,intro,done) on pp.programme_id=12 and ps.stable_key=v.session_key on conflict (session_id,language) do update set name=excluded.name,intro=excluded.intro,completion_message=excluded.completion_message;
insert into public.programme_session_exercises (session_id,exercise_id,exercise_variant_id,sort_order,is_optional,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select ps.id,e.id,ev.id,v.sort_order,false,v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-pacing-a','special-populations-breathing-pacing',null::text,0,2,6,5,30,'slow-controlled'),('session-pacing-a','special-populations-seated-mobility',null::text,1,2,6,null::integer,30,'slow-controlled'),('session-pacing-a','special-populations-supported-sit-to-stand','high-chair-full-support',2,2,4,null::integer,60,'controlled'),
('session-transfer-b','special-populations-seated-mobility',null::text,0,2,8,null::integer,30,'slow-controlled'),('session-transfer-b','special-populations-supported-sit-to-stand','standard-supported',1,2,6,null::integer,60,'controlled'),('session-transfer-b','special-populations-supported-weight-shift',null::text,2,3,6,null::integer,30,'slow-controlled'),
('session-balance-a','special-populations-supported-sit-to-stand','standard-supported',0,2,6,null::integer,60,'controlled'),('session-balance-a','special-populations-supported-weight-shift',null::text,1,3,6,null::integer,30,'slow-controlled'),('session-balance-a','special-populations-supported-march','short-bout',2,2,6,null::integer,45,'controlled'),
('session-walking-b','special-populations-supported-sit-to-stand','slow-lowering-supported',0,3,6,null::integer,75,'3-second-lowering'),('session-walking-b','special-populations-supported-weight-shift',null::text,1,3,6,null::integer,30,'slow-controlled'),('session-walking-b','special-populations-supported-march','standard-bout',2,2,8,null::integer,45,'controlled')) v(session_key,exercise_key,variant_key,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on pp.programme_id=12 and ps.stable_key=v.session_key join public.exercises e on e.stable_key=v.exercise_key left join public.exercise_variants ev on ev.exercise_id=e.id and ev.stable_key=v.variant_key
on conflict (session_id,sort_order) do update set exercise_id=excluded.exercise_id,exercise_variant_id=excluded.exercise_variant_id,is_optional=excluded.is_optional,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;