insert into public.programme_phases (programme_id,stable_key,sort_order,status) values (11,'mobility-foundation',0,'draft'),(11,'integrated-flow',1,'draft') on conflict (programme_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status;
insert into public.programme_phase_translations (phase_id,language,name,objective)
select pp.id,v.language,v.name,v.objective from public.programme_phases pp join (values
('mobility-foundation','fr','Phase 1 — Mobilité fondamentale','Développer une routine douce de respiration, rotation, mobilité de hanche et souplesse.'),('mobility-foundation','en','Phase 1 — Mobility foundations','Build a gentle routine of breathing, rotation, hip mobility, and flexibility.'),('mobility-foundation','de','Phase 1 — Mobilitätsgrundlagen','Sanfte Routine aus Atmung, Rotation, Hüftbeweglichkeit und Flexibilität aufbauen.'),
('integrated-flow','fr','Phase 2 — Mobilité intégrée','Enchaîner les mouvements de façon contrôlée pour entretenir la fonction et la souplesse.'),('integrated-flow','en','Phase 2 — Integrated mobility','Link movements with control to maintain function and flexibility.'),('integrated-flow','de','Phase 2 — Integrierte Mobilität','Bewegungen kontrolliert verbinden, um Funktion und Beweglichkeit zu erhalten.')) v(phase_key,language,name,objective) on pp.programme_id=11 and pp.stable_key=v.phase_key on conflict (phase_id,language) do update set name=excluded.name,objective=excluded.objective;
insert into public.programme_sessions (phase_id,stable_key,sort_order,status,estimated_duration_minutes)
select pp.id,v.stable_key,v.sort_order,'draft',v.minutes from public.programme_phases pp join (values ('mobility-foundation','session-reset-a',0,12),('mobility-foundation','session-mobility-b',1,14),('integrated-flow','session-flow-a',0,15),('integrated-flow','session-maintenance-b',1,16)) v(phase_key,stable_key,sort_order,minutes) on pp.programme_id=11 and pp.stable_key=v.phase_key on conflict (phase_id,stable_key) do update set sort_order=excluded.sort_order,status=excluded.status,estimated_duration_minutes=excluded.estimated_duration_minutes;
insert into public.programme_session_translations (session_id,language,name,intro,completion_message)
select ps.id,v.language,v.name,v.intro,v.done from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-reset-a','fr','Séance 1 — Respiration et rotation','Commencez par relâchement et mobilité thoracique.','Terminé : la mobilité doit rester confortable.'),('session-reset-a','en','Session 1 — Breathing and rotation','Start with relaxation and thoracic mobility.','Complete: mobility should remain comfortable.'),('session-reset-a','de','Einheit 1 — Atmung und Rotation','Mit Entspannung und Brustwirbelsäulenmobilität beginnen.','Fertig: Beweglichkeit soll angenehm bleiben.'),
('session-mobility-b','fr','Séance 2 — Hanches et mollets','Ajoutez charnière de hanche et souplesse du mollet.','Terminé : évitez toute recherche d’étirement maximal.'),('session-mobility-b','en','Session 2 — Hips and calves','Add hip hinge and calf flexibility.','Complete: avoid maximal stretching.'),('session-mobility-b','de','Einheit 2 — Hüften und Waden','Hüftbeugen und Wadenbeweglichkeit ergänzen.','Fertig: keine maximale Dehnung anstreben.'),
('session-flow-a','fr','Séance 3 — Flow contrôlé','Combinez mobilité du haut du dos, hanche et flow avec appui.','Terminé : gardez une respiration fluide.'),('session-flow-a','en','Session 3 — Controlled flow','Combine upper-back mobility, hip movement, and supported flow.','Complete: keep breathing smooth.'),('session-flow-a','de','Einheit 3 — Kontrollierter Flow','Oberen Rücken, Hüfte und unterstützten Flow kombinieren.','Fertig: ruhig weiteratmen.'),
('session-maintenance-b','fr','Séance 4 — Routine de maintien','Assemblez une courte routine réutilisable de mobilité globale.','Terminé : privilégiez régularité et confort.'),('session-maintenance-b','en','Session 4 — Maintenance routine','Assemble a short reusable whole-body mobility routine.','Complete: prioritise consistency and comfort.'),('session-maintenance-b','de','Einheit 4 — Erhaltungsroutine','Kurze wiederverwendbare Ganzkörper-Mobilitätsroutine zusammenstellen.','Fertig: Regelmäßigkeit und Komfort priorisieren.')) v(session_key,language,name,intro,done) on pp.programme_id=11 and ps.stable_key=v.session_key on conflict (session_id,language) do update set name=excluded.name,intro=excluded.intro,completion_message=excluded.completion_message;
insert into public.programme_session_exercises (session_id,exercise_id,exercise_variant_id,sort_order,is_optional,sets_override,repetitions_override,hold_seconds_override,rest_seconds_override,tempo_override)
select ps.id,e.id,ev.id,v.sort_order,false,v.sets_override,v.reps_override,v.hold_override,v.rest_override,v.tempo_override from public.programme_sessions ps join public.programme_phases pp on pp.id=ps.phase_id join (values
('session-reset-a','mobility-flexibility-breathing-reset',null::text,0,2,6,5,20,'slow-controlled'),('session-reset-a','mobility-flexibility-thoracic-rotation',null::text,1,2,6,null::integer,20,'slow-controlled'),('session-reset-a','mobility-flexibility-hip-hinge','hands-supported',2,2,6,null::integer,30,'controlled'),
('session-mobility-b','mobility-flexibility-thoracic-rotation',null::text,0,2,6,null::integer,20,'slow-controlled'),('session-mobility-b','mobility-flexibility-hip-hinge','standard',1,2,8,null::integer,30,'controlled'),('session-mobility-b','mobility-flexibility-calf-stretch',null::text,2,2,3,20,20,'steady'),
('session-flow-a','mobility-flexibility-thoracic-rotation',null::text,0,2,6,null::integer,20,'slow-controlled'),('session-flow-a','mobility-flexibility-hip-hinge','standard',1,2,8,null::integer,30,'controlled'),('session-flow-a','mobility-flexibility-supported-flow','small-range',2,2,4,null::integer,30,'slow-controlled'),
('session-maintenance-b','mobility-flexibility-calf-stretch',null::text,0,2,3,20,20,'steady'),('session-maintenance-b','mobility-flexibility-hip-hinge','slower-tempo',1,3,8,null::integer,45,'3-second-lowering'),('session-maintenance-b','mobility-flexibility-supported-flow','standard-flow',2,2,6,null::integer,30,'slow-controlled')) v(session_key,exercise_key,variant_key,sort_order,sets_override,reps_override,hold_override,rest_override,tempo_override) on pp.programme_id=11 and ps.stable_key=v.session_key join public.exercises e on e.stable_key=v.exercise_key left join public.exercise_variants ev on ev.exercise_id=e.id and ev.stable_key=v.variant_key
on conflict (session_id,sort_order) do update set exercise_id=excluded.exercise_id,exercise_variant_id=excluded.exercise_variant_id,is_optional=excluded.is_optional,sets_override=excluded.sets_override,repetitions_override=excluded.repetitions_override,hold_seconds_override=excluded.hold_seconds_override,rest_seconds_override=excluded.rest_seconds_override,tempo_override=excluded.tempo_override;